### ISSUE TITLE
Plugins shouldn't use shared config

### ISSUE THREAD

**Issue by Everettss** [vercel/next-plugins#128]
With current plugins setup, configurations are not [flexible](https://github.com/zeit/next-plugins/issues/97#issuecomment-375865251). I propose to change plugin configs api to a new one:

```
plugin(pluginConfig)(nextConfig)
```

This simple change enabled new powerful modification like this ones:

- cssModules per configs

`next.config.js `
```javascript
const withSCSSPlugin = require('@zeit/next-sass');
const withCSSPlugin = require('@zeit/next-css');

const webpackConfig = {
    webpack(config) {
        // bug workaround https://github.com/zeit/next-plugins/issues/127#issuecomment-377905928
        return commonChunkConfig(config, /\.(sass|scss|css)$/);
    },
};

const withCSS = withCSSPlugin({
    cssModules: false
});

const withSCSS = withSCSSPlugin({
    cssModules: true
});

module.exports = withCSS(withSCSS(webpackConfig));

```

this code will work:

```javascript
import 'extra-libray-from-npm/style.css' // disable cssModules
import s from './my-style.scss' // enable cssModules
```

- [different configs](https://github.com/zeit/next-plugins/issues/97#issuecomment-377787181) for the same loader 

`next.config.js `
```javascript
const withCSSPlugin = require('@zeit/next-css');

const withCSSWithoutNodeModules = withCSSPlugin({
    cssModules: true,
    moduleOptions: { // its easy to add this kind of option with this plugins api
        exclude: /node_modules/
    }
});

const withCSSNodeModules = withCSSPlugin({
    cssModules: false,
    moduleOptions: {
        include: /node_modules/
    }
});

module.exports = withCSSWithoutNodeModules(withCSSNodeModules());

```
this code will work:

```javascript
import 'extra-libray-from-npm/style.css' // disable cssModules
import s from './my-style.css' // enable cssModules
```

Here is example of implementation of this idea (for [next-css](https://github.com/zeit/next-plugins/blob/master/packages/next-css/index.js)):

```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const cssLoaderConfig = require('./css-loader-config')
const commonsChunkConfig = require('./commons-chunk-config')

module.exports = (pluginConfig = {}) => (nextConfig = {}) => {
    return Object.assign({}, nextConfig, {
        webpack(config, options) {
            if (!options.defaultLoaders) {
                throw new Error(
                    'This plugin is not compatible with Next.js versions below 5.0.0 https://err.sh/next-plugins/upgrade'
                )
            }

            const { dev, isServer } = options
            const { cssModules, cssLoaderOptions, moduleOptions } = pluginConfig

            // Support the user providing their own instance of ExtractTextPlugin.
            // If extractCSSPlugin is not defined we pass the same instance of ExtractTextPlugin to all css related modules
            // So that they compile to the same file in production
            let extractCSSPlugin =
                pluginConfig.extractCSSPlugin || options.extractCSSPlugin

            if (!extractCSSPlugin) {
                extractCSSPlugin = new ExtractTextPlugin({
                    filename: 'static/style.css'
                })
                config.plugins.push(extractCSSPlugin)
                options.extractCSSPlugin = extractCSSPlugin
                if (!isServer) {
                    config = commonsChunkConfig(config)
                }
            }

            options.defaultLoaders.css = cssLoaderConfig(config, extractCSSPlugin, {
                cssModules,
                cssLoaderOptions,
                dev,
                isServer
            })

            config.module.rules.push(Object.assign({}, {
                test: /\.css$/,
                use: options.defaultLoaders.css
            }, moduleOptions || {}))

            if (typeof nextConfig.webpack === 'function') {
                return nextConfig.webpack(config, options)
            }

            return config
        }
    })
}
```

**Comment by sonbuiGFD** [comment]
Thanks @Everettss,

import 'extra-libray-from-npm/style.css' // disable cssModules
import s from './my-style.scss' // enable cssModules
This is what I'm looking for.

Is this pull request yet? and can use this configuration without change next-plugins in node_modules?

**Comment by Everettss** [comment]
@sonbuiGFD No it's only a proposition - quite breaking change I think. It will be awkward when only one plugin changed that dramatically API.

**Comment by PitnerT** [comment]
Is there a workaround for now?

**Comment by YUFENGWANG** [comment]
is there a workaround for now ? 
import 'extra-libray-from-npm/style.less' // disable lessModules
import s from './my-style.scss' // enable cssModules
This is what I'm looking for.

**Comment by sheerun** [comment]
I'm looking for a way to configure next-images plugin so in development it doesn't inline any images. Basically I need to somehow pass option as so: `{ inlineImageLimit: dev ? 0 : 8192 }`, but I have no idea how can I easily do it. Maybe @timneutkens has some idea?

**Comment by sheerun** [comment]
I think it can be solved with following `next.config.js`:

```
const {PHASE_DEVELOPMENT_SERVER} = require('next/constants')
module.exports = (phase, {defaultConfig}) => {
  let dev = false

  if(phase === PHASE_DEVELOPMENT_SERVER) {
    dev = true
  }

  return nextImages({ inlineImageLimit: dev ? 0 : 8192 })(defaultConfig)
}
```

**Comment by sheerun** [comment]
Still, it's unfortunate that plugins consume their configuration in the same object they decorate

**Comment by timneutkens** [comment]
I'm okay with changing the signature of plugins to:

```
const withCSS = require('@zeit/next-css')({/* config */})
module.exports = withCSS()
```

If we can provide backwards compat that'd be great.

**Comment by sheerun** [comment]
OK, here's my try... beware, dragons ahead

Well at this point it's not easy to be backward compatible as this case is ambiguous:

```javascript
module.exports = withCSS()
```

Because `withCSS()` cannot possibly know whether it should return `(config) => config` decorator function, or just `config`, like it is doing now. It's even worse with composition, because following cases would need to be supported:

```javascript
module.exports = withPreact(withCSS({ cssModules: true }))
// or
module.exports = withCSS({ cssModules: true, ...withPreact() })
```

So both withPreact and withCSS would need to magically know whether caller expects it to return `config` or `config => config` (not possible).

Probably the only way to deal with these issues right now in backward-compatible way is to create next.js helper for composing plugins that sets global variable for the duration of composing which causes all plugins to return decorators instead of config.

Change to withCSS implementation would be minimal and would be few extra lines at the beginning:

```javascript
const cssLoaderConfig = require('./css-loader-config')

module.exports = (nextConfig = {}) => {
  if (global.__NEXT_COMPOSING__) {
    return nextConfig => withCss(Object.assign({}, optionsOrConfig, nextConfig))
  }

  // ... same code as before
}
```

And the usage as follows:

```javascript
// Old way (still supported)
const withCSS = require('@zeit/next-css')
const withPreact = require('@zeit/next-preact')

module.exports = withCSS({ ...withPreact(), cssModules: true })
```

```javascript
// New way (with composing helper)
const nextPlugin = require('@zeit/next-plugin')
const withCSS = require('@zeit/next-css')
const withPreact = require('@zeit/next-preact')

module.exports = nextPlugin(phase => [
  withCSS({ cssModules: true }),
  withPreact()
])
```

The implementation of nextPlugin is something as follows (could also support other definitions)

```javascript
module.exports = function (define) {
  return (options, config) => {
    let plugin = config => config
    global.__NEXT_COMPOSING__ = true
    define(options).forEach(decorator => {
      plugin = decorator(plugin)
    })
    delete global.__NEXT_COMPOSING__
    return plugin(config)
  }
}
```

It would be even nicer if interface of function exported from `next.config.js` changed from `(options, config) => config` to `(options) => (config) => config` (the same as plugins!). In this case the implementation of `nextPlugin` would be as follows:

```javascript
module.exports = function (define, legacy = false) {
  return options => {
    if (legacy && !global.__NEXT_COMPOSING__) {
      return define(options)(options)
    }
    let plugin = config => config
    const wereComposing = global.__NEXT_COMPOSING__
    global.__NEXT_COMPOSING__ = true
    const definition = define(options)
    if (typeof definition === "function") {
      plugin = definition(plugin)
    } else {
      definition.forEach(decorator => {
        plugin = decorator(plugin)
      })
    }
    global.__NEXT_COMPOSING__ = wereComposing
    return plugin
  }
}
```

And the implementation of withCss would be changed to:

```javascript
const nextPlugin = require('@zeit/next-plugin')
const cssLoaderConfig = require('./css-loader-config')

module.exports = cssLoaderConfig((pluginOptions = {}) => (nextConfig = {}) => {
  // ... same code as before
  const { cssModules, cssLoaderOptions, postcssLoaderOptions } = pluginOptions
  // ... same code as before
}, true)
```

The `legacy` flag basically tells whether to return backward-compatible `config => config` instead of `options => config => config` plugin (it wouldn't be used by e.g. `@zeit/next-source-maps` because it already has `options => config => config` interface by default).  At some point in the future extra `legacy` option and `__NEXT_COMPOSING__` lines could be removed.

**Comment by timneutkens** [comment]
Sounds like we should opt for a new major version of the plugins with err.sh link showing what changed.

**Comment by wouterds** [comment]
I agree they shouldn't use a shared config. Even for very basic use cases such as having css modules enabled except for vendor css this is currently really hard to do.

**Comment by georgii-ivanov** [comment]
it would be nice to have official compose package supported by @zelt.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
