### ISSUE TITLE
withCSS doesn't export all component-styles (randomly?)

### ISSUE THREAD

**Issue by schoenwaldnils** [vercel/next-plugins#133]
Currently I have the problem, that not all components are exported equally.

For example my base styles here: 
[schoenwaldnils/blog/pages/page.js#L5](https://github.com/schoenwaldnils/blog/blob/redesign/pages/page.js#L5)
and the component `Disqus`:
[schoenwaldnils/blog/pages/page.js#L11](https://github.com/schoenwaldnils/blog/blob/redesign/pages/page.js#L11)
are exported in the `/_next/static/style.css` which you can find here: [`style.css`](https://test.schoenwald.media/_next/static/style.css)

**BUT** the other components that are written the same, and are siblings of the working `Disqus` (like [`Post`](https://github.com/schoenwaldnils/blog/blob/redesign/pages/page.js#L9) are not exported.

And I sadly have no clue what that is.
Any ideas?

Edit:
I occasionally had/have similar problems with my local development environment.
But only with one component, and only sometimes.

package | version
-- | --
next | ~5.1.0
@zeit/next-css | ~0.1.5

**Comment by uuau99999** [comment]
Same problem. But withCss works perfectly in production mode with all css bundled while only extra part of all css in dev mode, which is pretty strange. - -

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
