### ISSUE TITLE
Support to put styles in head of doc and write to js files in bundle (like styled-jsx)

### ISSUE THREAD

**Issue by afzal273** [vercel/next-plugins#160]
One of the awesome features that styled-jsx gave us is the ability to create a js bundle for each page with css embedded and next-sass only allows for a global css file for the whole site rather than per page js. 

Is there any way to import sass files and still write to one js file per page and put styles in the head of the document?

**Comment by aequasi** [comment]
Any way to bundle css into pages would be amazing. Really a big feature thats missing here.

**Comment by gurmeetsinghmalhotra** [comment]
@afzal273 @aequasi  did you found a workaround?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
