### ISSUE TITLE
Warning: Prop `className` did not match. Server: "null"

### ISSUE THREAD

**Issue by rosancoderian** [vercel/next-plugins#165]
when i add :local it worked, but then i get this error after i refresh the page.
if i remove :local, then i add it again it will work again, but i still get the same error after i refresh the page.
```
// .next.config.js
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  // cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  }
})
```
```
// assets/style.css
body {
    background-color: blue;
}

:local .white {
    color: #fff;
}

.green {
    color: green;
}
```
```
// pages/index.js
import { Fragment } from 'react'
import css from '../assets/style.css'

export default () => (
    <Fragment>
        <p className={css.white}>index</p>
    </Fragment>
)
```

**Comment by yxqme** [comment]
Meet the same problem

**Comment by Kyle-Mendes** [comment]
This cropped up for me in nextCss `"0.2.1-canary.4"`

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
