### ISSUE TITLE
Is there any way to extend postcss.config.js asynchronously?

### ISSUE THREAD

**Issue by cyrstron** [vercel/next-plugins#213]
Hi,

I use next-css for bundling CSS-files. And all resourses, such as images or fonts, are stored on our CDN. I have to consider that CDN can be changed, so I'd like to get that CDN url from our headless CMS and use it for bundling CSS-files after that. As mentioned in offical Webpack documentation, Webpack allows to export functions that return promises in webpack.config.js:
```
module.exports = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve({
        entry: './app.js',
        /* ... */
      });
    }, 5000);
  });
};
```

But when i do the same for postcss.config.js, extension of config just doesn't happen:

```
module.exports = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res({
        plugins: {
          'cssnano': {},
          'postcss-prefix-url': {
            prefix: 'http://some.cdn.url',
          },
        },
      });
    }, 1000);
  });
};
```

Is there any other way to pass asynchronous property to postcss.config?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
