### ISSUE TITLE
Unable to use inline CSS after switching to mini-css-extract-plugin

### ISSUE THREAD

**Issue by kachkaev** [vercel/next-plugins#238]
Since recently (https://github.com/zeit/next-plugins/pull/228), it is no longer necessary to add `<link rel="stylesheet" href="/_next/static/style.css" />` to `_document.js` because `<link rel="stylesheet" href="/_next/static/css/styles.HASH.chunk.css"/>` is appended automatically. This is easy for developers, but comes at a cost for users. In my case, it blocks rendering by ≈1 second and shows the following warning in the [lighthouse](https://developers.google.com/web/tools/lighthouse/) report:

> External stylesheets are blocking the first paint of your page. Consider delivering critical CSS via
> `<style>` tags and deferring non-critical styles.

See original discovery of this performance issue in https://github.com/zeit/next-plugins/issues/11#issuecomment-376125174.

It'd be great to be able to use `<style>...inline...</style>` instead of `<link rel="stylesheet" />` (perhaps, as an opt-in). This approach would be especially useful in a project with `styled-components`, where pretty much anything except [normalize.css](https://necolas.github.io/normalize.css/) and a couple of global CSS rules is added to the body of a page by that library. How could we use inline styles in `_document.js`?

**Comment by dotlouis** [comment]
Same problem here.
Having a way to import styles and inline them would be very helpful to improve perf.
Any update on this?

**Comment by arianon** [comment]
For anyone still having this issue, this is the solution I came up with.

```jsx
import Document, { Head, Main, NextScript } from "next/document" 
import { readFileSync } from "fs"
import { join } from "path"

class InlineStylesHead extends Head {
  getCssLinks() {
    return this.__getInlineStyles()
  }

  __getInlineStyles() {
    const { assetPrefix, files } = this.context._documentProps
    if (!files || files.length === 0) return null

    return files.filter(file => /\.css$/.test(file)).map(file => (
      <style
        key={file}
        nonce={this.props.nonce}
        data-href={`${assetPrefix}/_next/${file}`}
        dangerouslySetInnerHTML={{
          __html: readFileSync(join(process.cwd(), ".next", file), "utf-8")
        }}
      />
    ))
  }
}

export default class CustomDocument extends Document {
  render() {
    return (
      <html>
        <InlineStylesHead />
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

Note the use of `data-href` prop, that is necessary to avoid fetching the CSS file unecessarily, see webpack-contrib/mini-css-extract-plugin#90

**Comment by kachkaev** [comment]
This is a great finding @arianon! Here's a small improvement from my side:

```diff
  import Document, { Head, Main, NextScript } from "next/document" 
  import { readFileSync } from "fs"
+ import { memoize } from "lodash";
  import { join } from "path"

+ const doGetContent = (file) =>
+   readFileSync(resolve(process.cwd(), ".next", file), "utf8");
+ const getContent =
+   process.env.NODE_ENV === "production" ? memoize(doGetContent) : doGetContent;

  class InlineStylesHead extends Head {
    getCssLinks() {
      return this.__getInlineStyles()
    }

    __getInlineStyles() {
      const { assetPrefix, files } = this.context._documentProps
      if (!files || files.length === 0) return null

      return files.filter(file => /\.css$/.test(file)).map(file => (
        <style
          key={file}
          nonce={this.props.nonce}
          data-href={`${assetPrefix}/_next/${file}`}
          dangerouslySetInnerHTML={{
-           __html: readFileSync(join(process.cwd(), ".next", file), "utf-8")
+           __html: getContent(file)
          }}
        />
      ))
    }
  }

  export default class CustomDocument extends Document {
    render() {
      return (
        <html>
          <InlineStylesHead />
          <body>
            <Main />
            <NextScript />
          </body>
        </html>
      )
    }
  }
```

By using [`memoize`](https://lodash.com/docs/4.17.11#memoize) or any similar wrapper function in production, you significantly reduce the number of times `readFileSync` gets invoked. CSS files are actually read only during the very first render of `_document` and their content is kept in memory until the process is stopped. Fewer synchronous calls to the filesystem → less frequent blocks of the main thread → quicker response times! 🎉 

One caveat I'm still keeping in mind is related to use of `process.cwd()`. Its presence means that the app can only be started from the project root and not any other folder. I know that that's an edge case, but it'd be still great to leverage Next's `config` → `distDir` somehow. I could not find this value in `this.context` or elsewhere while inside `_document`; if anyone knows how to get it, feel free to share!

**Comment by badpenguin** [comment]
Does not work for me, it tries to copy css from ./_next/ but instead the css is inside ./out/_next/
Is there a way to add the correct path prefix?

**Comment by virzak** [comment]
This is a great solution!
The only issue is when scss gets modified, there is no automatic refresh. The only way is F5. Any idea how to resolve that?

**Comment by badpenguin** [comment]
It works for me in v7 https://github.com/badpenguin/nextjs-static-generator-boilerplate
But in v8.1 there is some weird things happening with this.context._documentProps.files  https://github.com/zeit/next.js/issues/7641

**Comment by HimanJusta** [comment]
> For anyone still having this issue, this is the solution I came up with.
> 
> ```js-jsx
> import Document, { Head, Main, NextScript } from "next/document" 
> import { readFileSync } from "fs"
> import { join } from "path"
> 
> class InlineStylesHead extends Head {
>   getCssLinks() {
>     return this.__getInlineStyles()
>   }
> 
>   __getInlineStyles() {
>     const { assetPrefix, files } = this.context._documentProps
>     if (!files || files.length === 0) return null
> 
>     return files.filter(file => /\.css$/.test(file)).map(file => (
>       <style
>         key={file}
>         nonce={this.props.nonce}
>         data-href={`${assetPrefix}/_next/${file}`}
>         dangerouslySetInnerHTML={{
>           __html: readFileSync(join(process.cwd(), ".next", file), "utf-8")
>         }}
>       />
>     ))
>   }
> }
> 
> export default class CustomDocument extends Document {
>   render() {
>     return (
>       <html>
>         <InlineStylesHead />
>         <body>
>           <Main />
>           <NextScript />
>         </body>
>       </html>
>     )
>   }
> }
> ```
> 
> Note the use of `data-href` prop, that is necessary to avoid fetching the CSS file unecessarily, see [webpack-contrib/mini-css-extract-plugin#90](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90)

@arianon This solution works in my local server, but when i try to deploy it to my now server Im getting following error ```Error: ENOENT: no such file or directory, open '/var/task/_next/static/css/commons.b2e899ec.chunk.css'``` Do you know a workaround for this or faced a similar situation

**Comment by arianon** [comment]
@HimanJusta I tried to replicate your error (I don't use Zeit Now) but it works fine. https://himanjusta-issue-238-comment.arianon.now.sh/

Thought that file path in the error does seem weird to me, shouldn't the path be `/var/task/.next/static/css/commons.b2e899ec.chunk.css`? note the `.` in `.next`

**Comment by HimanJusta** [comment]
> @HimanJusta I tried to replicate your error (I don't use Zeit Now) but it works fine. https://himanjusta-issue-238-comment.arianon.now.sh/
> 
> Thought that file path in the error does seem weird to me, shouldn't the path be `/var/task/.next/static/css/commons.b2e899ec.chunk.css`? note the `.` in `.next`

Im facing this issue when i deploy to Zeit now, if I just use npm start and see the prod build on localhost it works. Regarding the error in file path I did notice that, but looks like zeit now uploads the next build to _next below is the snapshot of the final folder stucture in now
![Screenshot 2019-11-18 at 7 19 54 PM](https://user-images.githubusercontent.com/40352802/69057839-7ecc8380-0a38-11ea-97c1-a78c931da745.png)
![Screenshot 2019-11-18 at 7 21 05 PM](https://user-images.githubusercontent.com/40352802/69057905-9b68bb80-0a38-11ea-87f1-cee0b65bb377.png)

**Comment by michalisgar** [comment]
@HimanJusta same issue for me, too. Have you had any luck?

**Comment by yanv1991** [comment]
that won't work if your server load your css files from an external source like s3

**Comment by kachkaev** [comment]
A got a notification from github and was surprised to discover that this was my issue 😅

Nearly two years since creating it, I can say that I’ve solved this problem for myself by using [`styled-normalize`](https://www.npmjs.com/package/styled-normalize). Example:

* [`GlobalStyle.tsx`](https://github.com/kachkaev/njt/blob/9fdad2ca70621cfe5a2f4ba3851e15b7c9d5a6b7/src/ui/PageLayout/GlobalStyle.tsx)
* [`_document.tsx`](https://github.com/kachkaev/njt/blob/9fdad2ca70621cfe5a2f4ba3851e15b7c9d5a6b7/src/pages/_document.tsx#L32-L56)

Thus, in my recent apps, all styles come from [`styled-componets`](https://styled-components.com/) and there is not a single css file in the whole folder tree.

That said, I think it's worth keeping the issue open because it is still not possible to inline 'classic' css in Next. Just sharing this update to help folks who can use the same trick as me 🙌

**Comment by KATT** [comment]
@kachkaev yes, it's built-in, but it doesn't inline it on the page and I ended up here from googling on how to do it :)

I'm using a 

```jsx
import '../styles/all.scss';
```

in my `_app.js` and it ends up adding my CSS-file twice (once with `preload`, assumingly comes from it automatically preloading other routes or something?)

```html
<link rel="preload" href="/_next/static/css/63b012e1eea8af8f9e91.css" as="style"/><link rel="stylesheet" href="/_next/static/css/63b012e1eea8af8f9e91.css"/>
```

I simply have an old fashioned global SCSS-file - Ideally I would just embed it in a `<style>`-block on the page - does anyone know if this is possible?

**Comment by rstacruz** [comment]
The solution in https://github.com/vercel/next-plugins/issues/238#issuecomment-432211871 still works well today (Next.js 9.5, July 2020).

It gives a warning, though I don't think it'd cause any impact:

>  Warning: next-head-count is missing. https://err.sh/next.js/next-head-count-missing

**Comment by carloscuesta** [comment]
On `v9.5.2` which released today August 11, 2020. The solution at #238 returns the following error:

```
Unhandled error during request: TypeError: Cannot destructure property 'assetPrefix' of 'this.context._documentProps' as it is undefined.
```

You should now get this two variables from `this.context` to make it work again ✅ 

```js
const { assetPrefix, files } = this.context
```

**Comment by amineo** [comment]
In **v9.5.3**, `this.context` does not contain the `files` key so the solution outlined in #238 doesn't generate embedded styles anymore. It appears the previous files list has moved into the `buildManifest.pages` key where each page has its own list of files.

This minor change I did seems to fix it for me _(YMMV)_. I'm still getting my feet wet with Next so maybe someone with a little more experience can chime in to see if this is an appropriate fix? 


```diff
        __getInlineStyles() {
-               const { assetPrefix, files } = this.context;
+               const { assetPrefix, buildManifest } = this.context;
 
-               if (!files || files.length === 0) return null;
+               if (!buildManifest.pages || buildManifest.pages.length === 0) return null;
 
-               return files.filter((file) => /\.css$/.test(file)).map((file) => (
+               const pageKeys = [];
+               for (const key of Object.keys(buildManifest.pages)) {
+                       if (buildManifest.pages[key]) {
+                               pageKeys.push(buildManifest.pages[key]);
+                       }
+               }
+               const mergeDedupeFiles = (arr) => {
+                       return [ ...new Set([].concat(...arr)) ];
+               };
+
+               return mergeDedupeFiles(pageKeys).filter((file) => /\.css$/.test(file)).map((file) => (
                        <style
                                key={file}
                                nonce={this.props.nonce}
```

**My updated __getInlineStyles function**
```js
	__getInlineStyles() {
		const { assetPrefix, buildManifest } = this.context;

		if (!buildManifest.pages || buildManifest.pages.length === 0) return null;

		const pageKeys = [];
		for (const key of Object.keys(buildManifest.pages)) {
			if (buildManifest.pages[key]) {
				pageKeys.push(buildManifest.pages[key]);
			}
		}
		const mergeDedupeFiles = (arr) => {
			return [ ...new Set([].concat(...arr)) ];
		};

		return mergeDedupeFiles(pageKeys).filter((file) => /\.css$/.test(file)).map((file) => (
			<style
				key={file}
				nonce={this.props.nonce}
				data-href={`${assetPrefix}/_next/${file}`}
				dangerouslySetInnerHTML={{
					__html: fs.readFileSync(path.join(process.cwd(), '.next', file), 'utf-8')
				}}
			/>
		));
    }
```

Hope this helps someone!

**Comment by jsiddiqui** [comment]
In 9.5.3, `files` are passed as argument to `getCssLinks` so no need to go through `buildManifest`:

```  
getCssLinks({ allFiles }) {
  return allFiles
    .filter((file) => file.endsWith('.css'))
    .map((file) => (
      <style
        key={file}
        nonce={this.props.nonce}
        dangerouslySetInnerHTML={{
          __html: fs.readFileSync(path.join('.next', file), 'utf-8'),
        }}
      />
    ));
}
```

**Comment by deadcoder0904** [comment]
@jsiddiqui How do I do it in TypeScript?

When I click on `Head` in VSCode, I get the following:

```ts
getCssLinks(files: DocumentFiles): JSX.Element[] | null;
```

And `DocumentFiles` is defined as:

```ts
declare type DocumentFiles = {
    sharedFiles: readonly string[];
    pageFiles: readonly string[];
    allFiles: readonly string[];
};
```

Right now, I'm using `any` like:

```ts
getCssLinks({ allFiles }: { allFiles: any }) {
	const { assetPrefix } = this.context
	if (!allFiles || allFiles.length === 0) return null

	return allFiles
		.filter((file: any) => /\.css$/.test(file))
		.map((file: any) => (
			<style
				key={file}
				nonce={this.props.nonce}
				data-href={`${assetPrefix}/_next/${file}`}
				dangerouslySetInnerHTML={{
					__html: fs.readFileSync(path.join(process.cwd(), '.next', file), 'utf-8'),
				}}
			/>
		))
}
```

But why not export `DocumentFiles` so I can do the following instead:

```ts
getCssLinks({ allFiles }: DocumentFiles) {
  ...
}
```

**Comment by jsiddiqui** [comment]
@deadcoder0904 Specifying a type here is unnecessary as Typescript is able to infer the correct type due to extending the base class.

For example if you do this:
```
getCssLinks({ allFiles, test }) {
```

I get the following Typescript error:
```
src/pages/_document.tsx:9:3 - error TS2416: Property 'getCssLinks' in type 'InlineStylesHead' is not assignable to the same property in base type 'Head'.
  Type '({ allFiles, test }: { allFiles: any; test: any; }) => any' is not assignable to type '(files: DocumentFiles) => Element[]'.
    Types of parameters '__0' and 'files' are incompatible.
      Property 'test' is missing in type 'DocumentFiles' but required in type '{ allFiles: any; test: any; }'.
```

Therefore, I think that there is no need to export this.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
