### ISSUE TITLE
Using classnames-loader

### ISSUE THREAD

**Issue by guntherkoo** [vercel/next-plugins#246]
Hi, I'm trying to use classnames-loader as a webpack config but it doesn't seem to be working and I'm not sure why. 

`config.module.rules.push({
			test: /\.scss$/,
			use: [
				'classnames-loader',
				'style-loader',
				'css-loader?modules=1&sourceMap&importLoaders=1',
				'postcss-loader',
				'sass-loader?outputStyle=expanded'
			]
		});`

Does anyone have any insight on this? Huge thanks!

**Comment by jeremybarbet** [comment]
Hey @guntherkoo 

Any chance you came up with a fix at the end?

**Comment by guntherkoo** [comment]
Hi @jeremybarbet , yes I have. This snippet of code solved the issue I was running into and am able to use classnames-loader properly. 

`const sass = {
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[name]-[local]-[hash:base64:5]',
  },
  webpack: config => {
    config.module.rules.unshift({
      test: /\.scss$/,
      use: ['classnames-loader'],
    });
    return config;
  },
};`

Let me know if this works for you.

**Comment by jeremybarbet** [comment]
I have one issue: `Cannot find module '!../../../../../node_modules/classnames/bind.js'`

We have the `pages` folder that is just importing pages from `src/pages` and inside this, I have a `components` folder. So basically `src/pages/home/components/header/Header.tsx` it pops up this error with `classnames/bind`. I wish your solution would fix this too

**Comment by guntherkoo** [comment]
@jeremybarbet 

Do you have "classnames" and "classnames-loader node_modules installed? Also, I forgot to mention.. be sure to include that snippet in your next.config.js file.

**Comment by jeremybarbet** [comment]
Yeah I have unfortunately all this elements, but still not working: https://github.com/jeremybarbet/next-classnames-test/blob/master/next.config.js#L64-L78

**Comment by guntherkoo** [comment]
Where is `I have one issue: Cannot find module '!../../../../../node_modules/classnames/bind.js'` snippet coming from?

**Comment by jeremybarbet** [comment]
If you clone the repository and do `yarn build`/`yarn start` and go to the about page

**Comment by jeremybarbet** [comment]
FYI, we have been able to fix this issue by doing: https://github.com/ueno-llc/ueno-next-starter/blob/master/next.config.js#L30-L37 and using our own classnames-loader https://github.com/ueno-llc/next-classnames-loader#readme

(Also, you should close your issue if it's fixed for you)

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
