### ISSUE TITLE
How can I limit css modules to just .css files outside of node_modules?

### ISSUE THREAD

**Issue by geekyme** [vercel/next-plugins#301]
For instance, with this library http://react-day-picker.js.org/

My code:
```
import React from 'react';
import DayPicker from 'react-day-picker';
import 'react-day-picker/lib/style.css';
```

next.config.js:
```
const withCSS = require("@zeit/next-css");

module.exports = withCSS({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]"
  }
});
```

Right now all styles from `'react-day-picker/lib/style.css'` become css modules and the classes are auto suffixed. I don't want this behavior for my vendor styles. How do I do that?

**Comment by Uncleseneca** [comment]
#322

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
