### ISSUE TITLE
css plugin. Global by default

### ISSUE THREAD

**Issue by ramiel** [vercel/next-plugins#308]
I'd want to have css modules to be global by default. It means that

```css
:local(.top) {
   .bar {...}
}
```

would be transformed into 

```css
.top__random .bar {...}
```

Is there a way to achieve this?
Actually if I set `cssModules` to false this behavior is correctly working but only on client side, while on the server nothing is produced.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
