### ISSUE TITLE
Unable to import Font Awesome css, compile error

### ISSUE THREAD

**Issue by adueck** [vercel/next-plugins#310]
When trying to import the [Font Awesome](https://fontawesome.com/) css

```
import 'font-awesome/css/font-awesome.css';
```
It fails to compile with this error:

```
./node_modules/font-awesome/css/font-awesome.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

**Comment by lukeburns** [comment]
Same error importing tabler react's css, using next-css: 

```js
import "tabler-react/dist/Tabler.css";
```

**Comment by adueck** [comment]
It seems a lot of people are having the same issue with various css files, see issue #273

**Comment by penx** [comment]
Try this in `next.config.js`:

```js
const withTM = require('next-plugin-transpile-modules');

module.exports = withTM({
  transpileModules: ['tabler-react', 'font-awesome'],
...

**Comment by mattdamon108** [comment]
I have same issue here.
No luck with @penx's solution.

any solution?

**Comment by mattdamon108** [comment]
I found the one improvised solution and here I'd like to leave to share and provide a small clue to resolve this issue.

```js
// _document.jsx

<Head>
  <style>{`@import url(https://use.fontawesome.com/releases/v5.6.3/css/all.css)`}</style>
</Head>
```

This enables to use font awesome such as `<i className="fa fas-user-circle>` inside component.

**Comment by remy** [comment]
I found a work around (in my case I was using tabler-react) in Spectrum. [Original post here](https://spectrum.chat/next-js/general/import-css-from-node-modules~7c375fb6-4671-4f1b-a67f-dbfddd3528fe?m=MTU1MzA2ODIwOTczNQ==).

Solution (via @Vrq and @timneutkens): 

1. npm install --save @zeit/next-css
2. In `next.config.js`:

```js
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  cssLoaderOptions: { // this solves the issue
    url: false
  }
})
```
3. Now import works: `import 'tabler-react/dist/Tabler.css'`

**Comment by ertejaspatel** [comment]
Making url to false does fix compilation error but does not resolve font awesome fonts. 

Is there proper fix?

**Comment by Joao8** [comment]
Hi,

This worked for me: 
$ npm i --save @fortawesome/fontawesome-svg-core  @fortawesome/free-solid-svg-icons @fortawesome/react-fontawesome

import '@fortawesome/fontawesome-svg-core/styles.css' // Import the CSS

**Comment by Bacher** [comment]
> I found the one improvised solution and here I'd like to leave to share and provide a small clue to resolve this issue.
> 
> ```js
> // _document.jsx
> 
> <Head>
>   <style>{`@import url(https://use.fontawesome.com/releases/v5.6.3/css/all.css)`}</style>
> </Head>
> ```
> 
> This enables to use font awesome such as `<i className="fa fas-user-circle />` inside component.

You could add stylesheet easier:
```html
<link
  rel='stylesheet'
  media='screen, print, projection'
  href='https://use.fontawesome.com/releases/v5.14.0/css/all.css'
/>
``

**Comment by Adamkaram** [comment]
is there's any proper soluation?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
