### ISSUE TITLE
CSS Modules are not correctly be interpolated

### ISSUE THREAD

**Issue by nfrush** [vercel/next-plugins#312]
With Next 7, my Stylus -> CSS Modules are not correctly be interpolated.

For example, I can have one component use a style sheet with className 'container_header' and another component with 'container_footer' and both will be interpolated as 'container_header_1xS64' despite one not even referencing container_header.

Anyone else experience this? What the hell is up?

**Comment by timneutkens** [comment]
This issue is not really actionable without any reproduction

**Comment by MadsMadsDk** [comment]
I am experiencing this as well. 

In my case, I have a page with two adjacent components, inside a wrapper. Both components have their own scss module file, but as @nfrush is experiencing, both component classNames are interpolated to the last encountered components className.

I'm trying to recreate the issue for a debug repository you guys can take a look at.
@nfrush I'm experiencing the issue with SCSS as well. Can you tell me a bit more about packages you're using, that could be the culprit?

**Comment by MadsMadsDk** [comment]
Ooh, I've just found out what might be the culprit.

My two adjacent components are both <div>'s, but if I change one of them to be a <section> instead, it interpolates the className as expected.

**Comment by nfrush** [comment]
> Ooh, I've just found out what might be the culprit.
> 
> My two adjacent components are both `<div>`'s, but if I change one of them to be a `<section>` instead, it interpolates the className as expected.

This is EXACTLY what I'm experiencing. I'm using Stylus in place of SCSS, but same deal down to them both being <div>

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
