### ISSUE TITLE
CSS Error > Unexpected token . [react-flexbox-grid & next-css]

### ISSUE THREAD

**Issue by iammarkps** [vercel/next-plugins#318]
When I use react-flexbox-grid, This error shows up. This is my nextjs config
```
const withCSS = require('@zeit/next-css')
const withBundleAnalyzer = require('@zeit/next-bundle-analyzer')
module.exports = withCSS(
  withBundleAnalyzer({
    analyzeServer: ['server', 'both'].includes(process.env.BUNDLE_ANALYZE),
    analyzeBrowser: ['browser', 'both'].includes(process.env.BUNDLE_ANALYZE),
    bundleAnalyzerConfig: {
      server: {
        analyzerMode: 'static',
        reportFilename: '../bundles/server.html'
      },
      browser: {
        analyzerMode: 'static',
        reportFilename: '../bundles/client.html'
      }
    }
  })
)
```

Ref: https://github.com/zeit/next-plugins/issues/145
I see the fixed commit but still not working

**Comment by iammarkps** [comment]
Step to reproduce
1. Clone my repo: https://github.com/iammarkps/openhouse
2. yarn install
3. yarn dev

**Comment by andreystarkov** [comment]
same problem

**Comment by xeoneux** [comment]
I had a similar issue and solved it by generating a postcss config file in the 👍

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
