### ISSUE TITLE
exclude some libraries from being loaded with css-modules with next-css

### ISSUE THREAD

**Issue by Farideh** [vercel/next-plugins#319]
I'm using next-css like this:
`module.exports = withCss({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  },
  webpack (config) { ... `

I want to add an exception for rc-slider loading with css-modules. but I dont know how to do it.
any help?

**Comment by ZerdoX-x** [comment]
@WeiGrand thank you very much!

**Comment by ZerdoX-x** [comment]
Now if you use Next.js 9.2 and higher you don't need to use next-css for enabling CSS Module.
https://nextjs.org/blog/next-9-2

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.

**Comment by ZerdoX-x** [comment]
Yep, that's what i meant
