### ISSUE TITLE
Should css-loader be listed as Peer Dependency?

### ISSUE THREAD

**Issue by kochis** [vercel/next-plugins#325]
Using `yarn v1.10.1`

I have the following setup in my package.json
```js
"dependencies": {
  "@zeit/next-sass": "^1.0.1",
  ...
},
"devDependencies": {
  "css-loader": "^1.0.0",
}
```
When installing in production mode, `css-loader` is installed at `node_modules/@zeit/next-css/node_modules/css-loader/` which is expected since it's listed as a dependency of `@zeit/next-css`. However, I'm getting the following error when building:

```
> Failed to build
{ Error: (client) ./pages/_app.jsx
Module not found: Error: Can't resolve 'css-loader' in '/Users/.../Projects/frontend'
 @ ./pages/_app.jsx 32:0-23
 @ multi ./pages/_app.jsx
```

It looks like `css-loader` not actually required anywhere in the project, just referenced like so: https://github.com/zeit/next-plugins/blob/68b39d8c3ff21ce469c0ee79ac41ed06ca251367/packages/next-css/css-loader-config.js#L65

So I'm guessing node is looking in the root `node_modules/` folder for `css-loaders`, but it's not present (yarn is not hoisting it).

Adding `css-loader` to the dependencies resolves the issue, but there was no indication that it needed to be. Was wondering if either there's something wrong with my setup that causes it to be missing in prod, or if it should be listed as a peer dependency.

**Comment by kochis** [comment]
Also interesting, removing `css-loader` from the `devDependencies` also resolves the issue. Something about having it present in the `devDependencies` is preventing yarn from hoisting the package in a production environment.

**Comment by BlackShabat** [comment]
Had the same issue. Deleting the package-lock.json and node_modules helped. After reinstalling npm packages I saw css-loader package inside node_modules folder and error disappear

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
