### ISSUE TITLE
Various console errors with Preact plugin

### ISSUE THREAD

**Issue by luandro** [vercel/next-plugins#326]
Tried using the Preact plugin, added the `server.js` and `next.config.js` as instructed. I'm getting all these logs on the console:

```
Warning: Failed prop type: Link: unknown props found: __source, __self
```

```
Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/preact-compat/dist/preact-compat.es.js?. URL scheme must be "http" or "https" for CORS request.
```

```
Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/preact/dist/preact.mjs?. URL scheme must be "http" or "https" for CORS request.
```

```
Uncaught (in promise) Error: Cannot read property 'styleId' of null
```

Using latest version of everything.

**Comment by vorillaz** [comment]
Same issue as @luandro. I am assuming the preact plugin does not work properly with `styled-jsx`.

**Comment by Angelmmiguel** [comment]
Same here

**Comment by developit** [comment]
Subscribing to this issue. The Preact team is working on addressing this.

**Comment by timneutkens** [comment]
@developit you might want to check https://github.com/zeit/next.js/issues/5716

**Comment by developit** [comment]
Thanks @timneutkens - already have that one implemented in the upcoming Preact X release.

**Comment by markolofsen** [comment]
8.0.3 — the same problem
`Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/./node_modules/react-dom/cjs/react-dom.development.js?. URL scheme must be "http" or "https" for CORS request.`

**Comment by StarpTech** [comment]
Same with Next.js 9.0.8

```
Failed Link type: <Link href="[object Object]" as="/components/robots" __self="undefined" />: unknown props found: __self
```

**Comment by timneutkens** [comment]
The next-preact plugin has been deprecated in favor of the preact example.
