### ISSUE TITLE
next-bundle-analyzer not works properly

### ISSUE THREAD

**Issue by VBagmut** [vercel/next-plugins#332]
instead of opening file in browser it opens it in VS Code. Also openAnalyzer option with false value doesn't work. 
OS: Ubuntu 18.04
Next.js 7.0.2

**Comment by mohammad-amin-hesam** [comment]
same issue

ubuntu 18.04
next ^9.3.5

**Comment by millette** [comment]
Did you try with https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer ? I think the issue, if it remains, should be moved there too.
