### ISSUE TITLE
Beginner question: how to use next-less?

### ISSUE THREAD

**Issue by alucard001** [vercel/next-plugins#338]
Here is my package.json file config:

```
{
  "name": "my-app",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-less": "^1.0.1",
    "@zeit/next-typescript": "^1.1.1",
    "@zeit/next-workers": "^1.0.0",
    "dotenv": "^6.1.0",
    "less": "^3.8.1",
    "next": "7.0.2",
    "react": "16.6.3",
    "react-dom": "16.6.3",
    "typescript": "^3.1.6",
    "worker-loader": "^2.0.0"
  },
  "devDependencies": {
    "fork-ts-checker-webpack-plugin": "^0.4.15"
  }
}
```
And in my `/css/styles.less` file it is just simply:
```
.top_admin_bar{
    background-color: black;
}
```
In my `/pages/index.js`:
```
import React from 'react'
import Link from 'next/link'
import Head from '../components/head'
import Nav from '../components/nav'

const Home = () => (
	<div>
		<Head title="ChatBot Admin Dashboard" description="Chatbot admin dashboard" />
		<Nav />

	</div>
)
export default Home
```
And in `<Nav/>` inside `/components/nav.js`, it is:
```
import React from 'react'
import css from '../css/styles.less'

const Nav = () => (
  <nav>
    <div className="container-fluid">
      <div className = "row {css.top_admin_bar}">
        <div className="logo col-3">
          <ul className="nav justify-content-start">
            <li className="nav-item">
              <a className="nav-link" href="/">My Logo</a>
            </li>
          </ul>
        </div>
        <div className="other_links col-9">
          <ul className="nav justify-content-end">
            <li className="nav-item">
              <a className="nav-link active" href="#">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
)
export default Nav
```
What I want to do is to chagne the `top_admin_bar` background to black using CSS Less, but I tried the README in `next-less` it didn't work.

My Directory structure:
![001](https://user-images.githubusercontent.com/1968244/48768431-febff080-ecf3-11e8-8c4f-b78c8d155d9b.jpg)

Can anyone please help me on this?

Thank you very much in advance for all your help.

**Comment by kachkaev** [comment]
@alucard001 this official example might give you a clue: https://github.com/zeit/next.js/tree/canary/examples/with-next-less

If that does not help, feel free to ask your question in https://spectrum.chat/next-js. Github issues are mainly for bug reports and feature requests – it's somewhat harder to find support here.

**Comment by alucard001** [comment]
> @alucard001 this official example might give you a clue: https://github.com/zeit/next.js/tree/canary/examples/with-next-less
> 
> If that does not help, feel free to ask your question in https://spectrum.chat/next-js. Github issues are mainly for bug reports and feature requests – it's somewhat harder to find support here.

I am very sorry about that.
