### ISSUE TITLE
Doesn't read postcss config from package.json

### ISSUE THREAD

**Issue by lamartire** [vercel/next-plugins#342]
Issue for `@zeit/next-css`.

Hello! When I pass config of `postcss` to `package.json` – postcss doesn't work correctly, it ignores all plugins and configuration. But it woks fine if `postcss` config placed into `postcss.config.js`.

Thanks for awesome tool! 🙌

**Comment by kylemh** [comment]
That's expected.

https://github.com/zeit/next-plugins/tree/master/packages/next-css#postcss-plugins

Creating a `postcss.config.js` is currently the only accepted means of leveraging PostCSS.

**Comment by lamartire** [comment]
I think that is not good, because postcss and other packages, like `postcss-loader`, or `gulp-postcss` can read configuration from `package.json`.
May be I can help with that?

**Comment by kylemh** [comment]
I'm not a maintainer, but I think it can be done easily and maintainably 👍 

The spot you'll be worried about is here: https://github.com/zeit/next-plugins/blob/master/packages/next-css/css-loader-config.js#L59

You'll want to check for `postcss.config.js` first and then - if there's nothing - look inside `package.json`

**Comment by lamartire** [comment]
Ok, I will see during a few days 👍

**Comment by lamartire** [comment]
Hello! Look the #369 for more details.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
