### ISSUE TITLE
_app.tsx usage not supported

### ISSUE THREAD

**Issue by christophediprima** [vercel/next-plugins#343]
I have syntax errors when using typescript in _app.tsx.

**Comment by kachkaev** [comment]
Hi @christophediprima! Could you please share a minimal working example that reproduces the bug? Otherwise, there's no way other can help you as there is very little information in your report.

**Comment by christophediprima** [comment]
Sure! It looks like that adding any typescript syntax into an _app.tsx, is producing errors.
I am trying to add a redux-provider that contains some types inside of "pages/_app.tsx". But this simple code also 

```typescript
import React from "react";
import App, { Container } from "next/app";

type Foo = {
  bar: string;
};

const foo: Foo = {
  bar: "bar"
};

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    const pageProps = Component.getInitialProps
      ? await Component.getInitialProps(ctx)
      : {};
    console.log(foo);
    return { pageProps };
  }

  render() {
    const { Component, pageProps } = this.props;
    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    );
  }
}

export default MyApp;
```

This produces following error.
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                               3:59:31 PM

 error  in ./pages/_app.tsx

Syntax Error: SyntaxError: /Users/christophediprima/Projects/nextjs-test/pages/_app.tsx: Unexpected token, expected ";" (4:5)

  2 | import App, { Container } from "next/app";
  3 |
> 4 | type Foo = {
    |      ^
  5 |   bar: string;
  6 | };
  7 |
```

**Comment by kachkaev** [comment]
This listing is still not enough to help as it is not reproducible. The work of TypeScript depends on the contents of your package.json file and other things, not just what's in `_app.tsx`. I suggest looking at these examples
* https://github.com/zeit/next.js/tree/canary/examples/with-typescript
* https://github.com/zeit/next.js/tree/canary/examples/with-typescript

and sharing a _repo_ with a project if things still don't work after trying to figure out what's missing.

If you have found the cause of your issue, feel free to share it here to help other going down the same path after you.

**Comment by lostfictions** [comment]
I'm hitting a possibly-related issue; I was following the [with-apollo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) example, but using [@zeit/next-typescript](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript) in my `next.config.js`. It seems to choke on the generic syntax:

```
Syntax Error: SyntaxError: ~/repro/pages/_app.tsx: Unexpected token, expected "{" (8:28)

   6 | import withApolloClient from "../shared/apollo/with-apollo-client";
   7 | 
>  8 | class MyApp extends App<{
   9 |   apolloClient: ApolloClient<NormalizedCacheObject>;
  10 | }> {
  11 |   render() {
```

I unfortunately don't have time to make a minimal repro case right now but I can try to add one later.

**Comment by lostfictions** [comment]
Okay, egg on my face -- this is totally my fault. I hadn't created a `.babelrc` file in my project like the plugin requires. Everything works for me now~
