### ISSUE TITLE
[next-sass/next-css] CSS critical & media splitting with async bundles loading

### ISSUE THREAD

**Issue by cyrstron** [vercel/next-plugins#345]
Hi,

I'm trying to find a way to load styles bundle asyncrounously with ability to add critical part of styles to head as inline styles and split the rest of the bundle according to device resolution. Is there any way to implement it with next-css or next-sass?

At the moment I have duct tape solution with modifing of next/document Head for asyncronous styles loading and have no idea how to split the bundle to separate files.

    class ExtendedHead extends Head {
      getCssLinks() {
        return this.__getInlineStyles();
      }

      __getInlineStyles() {
         const {assetPrefix, files} = this.context._documentProps;
         if (!files || files.length === 0) return null;

         const stylesHrefs = files
           .filter((file => /\.css$/.test(file)))
           .map(file => `${assetPrefix}/_next/${file}`);

         const stylesIds = [];

         const stylesPreload = stylesHrefs.map((href, index) => {
         const id = `style-${index}`;

         stylesIds.push(id);
         return <link
            key={index}
            href={href}
            rel='preload'
            as='style'
            id={id}
          />;
        });

        const stylesSelector = stylesIds
          .map(styleId => `#${styleId}`)
          .join(', ');

         const asyncLoader = <script key="styles-loader"
          dangerouslySetInnerHTML={{__html: `
    var styles=document.querySelectorAll('${stylesSelector}');
    for(var i=0,len=styles.length;i<len;i+=1){
    styles[i].onload=function(){this.rel='stylesheet';this.onload=null}
    }`,
          }} />;

        const styles = stylesHrefs.map((href, index) => <link
          key={index}
          href={href}
          rel='stylesheet'
        />);

        return [
          ...stylesPreload,
          asyncLoader,
          <noscript key="noscript-styles">{styles}</noscript>,
        ];
      }
    };

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
