### ISSUE TITLE
Sass HMR not working

### ISSUE THREAD

**Issue by ushastikchb1** [vercel/next-plugins#353]
Good day!
I split my styles into several files, one for each page (index.scss, post.scss, post-list.scss).

indes.scss:
```
@import "./common";
...styles
```

post.scss:
```
@import "./common";
...styles
```

Import in each page:
/pages/index.js
`import "./../src/scss/index.scss"`, 

/pages/post.js
`import "./../src/scss/post.scss"`

next.config.js 
```
const withSass = require("@zeit/next-sass");

module.exports = withSass({
  distDir: 'build',
  useFileSystemPublicRoutes: false,
  webpackDevMiddleware: (config) => {
    return {
      ...config,
      watchOptions: {
        ...config.watchOptions,
        poll: true,
      }
    };
  },
  webpack: (config, { dev, isServer }) => {
    config.module.rules.push(
      {
        test: /\.(svg|eot|ttf|woff|woff2)$/,
        use: {
          loader: "url-loader",
          options: {
            limit: 100000,
            outputPath: "../static/fonts",
            publicPath: "/static/fonts",
          }
        }
      },
      {
        test: /\.(png|jpg|jpeg|gif|ico)$/,
        use: {
            loader: "file-loader",
            options: {
              name: "[name].[ext]",
              outputPath: "../static/images",
              publicPath: "/static/images",
              emitFile: !isServer,
            },
          },
      }
    );

    return config;
  }
});
```

When you open the main page, the css loads correctly. When you go to other pages are loaded all the same unchanged styles for the main page.

At the same time comes the update, but the code indicated by the arrow is not executed. 

![image](https://user-images.githubusercontent.com/5453621/49726017-16005700-fc7e-11e8-9ba4-d9ab6b6c2831.jpg)

At the same time, if you update a new page on f5, the styles are displayed correctly and after that, when you go to this page, everything will be fine.

What could be the reason?

**Comment by rohmann** [comment]
It's pretty much the same as this issue #282 

I'm solving it for the dev env with the following (derived from the comments on that issue) code placed at the top of `_app.js`. It's still not ideal because you get FOUC when navigating around.

```
import Router from 'next/router'
if (process.env.NODE_ENV !== 'production') {
  Router.events.on('routeChangeComplete', () => {
    const el = document.querySelector('link[href*="/_next/static/css/styles.chunk.css"]')
    if (!el) return
    el.href = '/_next/static/css/styles.chunk.css?v=' + new Date().valueOf()
  })
}
```

**Comment by icflorescu** [comment]
None of the workarounds I've found so far worked for me, so I've come up with a different one: https://github.com/zeit/next-plugins/issues/282#issuecomment-450578740

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
