### ISSUE TITLE
Path splitting for CSS modules

### ISSUE THREAD

**Issue by penx** [vercel/next-plugins#354]
I have a basic example project here:

https://github.com/penx/govuk-frontend-react-example-next

The CSS module for the `<Button /`> is only needed on the 'About' page, but is loaded in to the CSS on the home page.

There is an open PR for this but it hasn't been update for 3 months and there is no associated issue - https://github.com/zeit/next-plugins/pull/190

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
