### ISSUE TITLE
[@zeit/next-css] Have an option to inline imported css.

### ISSUE THREAD

**Issue by rtm619** [vercel/next-plugins#364]
Hi,

I have gone through all issues and even though #238 is a work-around, it doesn't help as the head contains duplicate <link> imports. I am currently using postcss with my next-css plugin. It'd be great if there's an option to inline imported css into a style tag in head to improve page load speed. 

Thanks in advance

**Comment by dazjavier** [comment]
Is there any updates on this? I would be happy to implement this.

**Comment by olpeh** [comment]
This would be handy. The workaround in #238 feels a bit dirty.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.

**Comment by olpeh** [comment]
Hi @timneutkens how does the built-in CSS support handle inlining the CSS? I can't see any references to that in the docs.
