### ISSUE TITLE
Resolve directories using webpack

### ISSUE THREAD

**Issue by amabunny** [vercel/next-plugins#366]
# Feature request

## Is your feature request related to a problem? Please describe.
My problem is related to resolve my project root directory. It is not a problem when i using ES with babel-plugin-module-resolver, but withTypescript preset it is not working.

## Describe the solution you'd like
https://github.com/zeit/next-plugins/issues/136#issuecomment-443666897
Think there is no way to resolve dir in typescript except include this to webpack config.
e.g.:
**next.config.js**: 
```
module.exports = withResolveDirs([
  './', './components'
])
```
or such arguments as you'd like. It will works fine with ES and Typescript.

## Describe alternatives you've considered
Only the specified github solution works.

Thx for your attention and have a nice day!

**Comment by iamgreyy** [comment]
Oh, sorry. I doesnt know about next-plugins repo. Ok, thx 4 u anyway.
