### ISSUE TITLE
Running two Next apps with next-css in the same Node process throws `TypeError: this[MODULE_TYPE] is not a function`

### ISSUE THREAD

**Issue by craigspaeth** [vercel/next-plugins#373]
Hello. I'm trying to run multiple Next apps in the same process following the [custom server and routing docs](https://github.com/zeit/next.js/#custom-server-and-routing) both using next-css. (FYI this was working before Next 7 and appears to be related to the [css-imports upgrade](https://nextjs.org/blog/next-7/#css-imports).)

When I do this one of the apps compiles CSS fine and the other produces this error:

```
./pages/index.css
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
```

It appears there is possibly some state being held inside [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin), or on the filesystem, that might be causing the Webpack builds for these two apps to conflict. I've created a [repo that reproduces the issue here](https://github.com/craigspaeth/next-7-mini-css-compile-error-example).

After researching some related issues it seems it's possible this could be related to HMR, but I'm having trouble narrowing down where the bug is occurring. Any help would be greatly appreciated and I'd be happy to move this issue to mini-css-extract-plugin and/or submit a pull request to patch the bug.

Thank you!

**Comment by tagyoureit** [comment]
I'm seeing this same error with both Next 7.0.2-canary-50 and 8.0.1.  In both instances everything works fine on my Macbook.  When copy files over to the Raspberry Pi and run `npm run dev` I am seeing this error.  Production builds don't have the error.

**Comment by kyle-mccarthy** [comment]
I am also having this problem and am fairly certain it is related to HMR.  Here is my error stack. This only happen in development when I have to different projects running using webpack + HMR.

```
TypeError: this[MODULE_TYPE] is not a function
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function
    at childCompiler.runAsChild (/../node_modules/mini-css-extract-plugin/dist/loader.js:141:24)
    at compile (/../node_modules/webpack/lib/Compiler.js:306:11)
    at hooks.afterCompile.callAsync.err (/../node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/../node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
```

**Comment by kyle-mccarthy** [comment]
I am not entirely sure how next handles webpack and the plugins but it looks like the list of plugins is different between calls to webpack in the next.config.js. 

_Note that I did switch next-css to `1.0.2-canary.2` to see if it would resolve the issue, but it didn't._

Initial call includes ExtractCssChunks

```
[ AutoDLLPlugin {...},
ChunkNamesPlugin {},
ReactLoadablePlugin { ... },
NextJsRequireCacheHotReloader { ... },
HotModuleReplacementPlugin { ... },
NoEmitOnErrorsPlugin {},
UnlinkFilePlugin { ... },
CaseSensitivePathsPlugin { ... },
DefinePlugin {...},
DefinePlugin {...},
BuildManifestPlugin {},
ExtractCssChunks {...} ]
```

Second call does not

```
[ ChunkNamesPlugin {},
  NextJsRequireCacheHotReloader { ... },
  NoEmitOnErrorsPlugin {},
  UnlinkFilePlugin { prevAssets: {} },
  CaseSensitivePathsPlugin { ... },
  DefinePlugin { ... },
  PagesManifestPlugin {},
  NextJsSsrImportPlugin {},
  NextJsSsrImportPlugin { ... } ]
```

This could just be me not understanding what next is doing but I think it would explain the missing plugin...

**Comment by craigspaeth** [comment]
I discovered that the problematic state is located on [this line of code](https://github.com/zeit/next-plugins/blob/master/packages/next-css/css-loader-config.js#L6) where the `extractCssInitialized` boolean appears to be preventing `ExtractCssChunks` from being initialized multiple times. I don't understand yet why that boolean is necessary, but removing it solves the issue.

**Comment by Lwdthe1** [comment]
I'm facing the same issue trying to run multiple apps with semantic-ui (fomantic). My stack trace:

```
Module build failed (from ./node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js): TypeError: this[MODULE_TYPE] is not a function at childCompiler.runAsChild (/myMonoRepo/web/ssoapp/manyStoriesv2/node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js:141:24) at compile (/myMonoRepo/node_modules/webpack/lib/Compiler.js:343:11) at hooks.afterCompile.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compiler.js:681:15) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at compilation.seal.err (/myMonoRepo/node_modules/webpack/lib/Compiler.js:678:31) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at hooks.optimizeAssets.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1423:35) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at hooks.optimizeChunkAssets.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1414:32) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at hooks.additionalAssets.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1409:36) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at hooks.optimizeTree.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1405:32) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at Compilation.seal (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1342:27) at compilation.finish.err (/myMonoRepo/node_modules/webpack/lib/Compiler.js:675:18) at hooks.finishModules.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1261:4) at AsyncSeriesHook.eval [as callAsync] (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1) at AsyncSeriesHook.lazyCompileHook (/myMonoRepo/node_modules/tapable/lib/Hook.js:154:20) at Compilation.finish (/myMonoRepo/node_modules/webpack/lib/Compilation.js:1253:28) at hooks.make.callAsync.err (/myMonoRepo/node_modules/webpack/lib/Compiler.js:672:17) at _err0 (eval at create (/myMonoRepo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)

```

**Comment by Lwdthe1** [comment]
@craigspaeth I curious if you found a way around it.

How I currently tried fixing it was to add that flagged portion of the code you linked to ([this line of code](https://github.com/zeit/next-plugins/blob/master/packages/next-css/css-loader-config.js#L6)) into my own next.config.js file:

```

// Patching bug.
			// See https://github.com/zeit/next-plugins/issues/373#issuecomment-500260362
			if (!isServer && !extractCssInitialized) {
				config.plugins.push(
					new ExtractCssChunks({
						// Options similar to the same options in webpackOptions.output
						// both options are optional
						filename: dev ? 'static/chunks/[name].css' : 'static/chunks/[name].[contenthash:8].css',
						chunkFilename: dev
							? 'static/chunks/[name].chunk.css'
							: 'static/chunks/[name].[contenthash:8].chunk.css',
						hot: dev,
					}),
				)
				extractCssInitialized = true
			}

```

I had add the webpack plugin to my dependencies. It worked when I added it to one of my projects. I'm not sure if I need to add it to both of my projects to avoid some race condition.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
