### ISSUE TITLE
Is it ok to use css-loader-config?

### ISSUE THREAD

**Issue by rkatic** [vercel/next-plugins#376]
On our projects we have to support four cases: both CSS and SASS, and **css-modules depending on location of files**. Although it is possible to combine `next-css` and `next-sass`, those are not configurable separately (both use same options from nextConfig), and do not provide other needed options (rule exclude/include.)

We ended up using `@zeit/next-css/css-loader-config` in four separate rules. All seems to work great.

Is this use expected? 
Will any breaking change in `css-loader-config` also result in a major release of `@zeit/next-css`?

**Comment by radeno** [comment]
@rkatic Every undocumented usage of code can be breaking change in every version. Only public official API following semantic versioning should not.
So you need to watch changes.

**Comment by rkatic** [comment]
@radeno that's how usually is. And almost positive that applies here too.
For example `@zeit/next-sass` uses `@zeit/next-css/css-loader-config` by depending to an exact version of `@zeit/next-css`. Since it is maintained by same people, that's fine, I guess.

If the above described use-case is not that rare, I would probably suggest to move `@zeit/next-css/css-loader-config` in a separate package so that others too can easily benefit from regular patches.

**Comment by radeno** [comment]
@rkatic i understand your concerns, but `next-sass` has dependency `next-css` but as you can see it is locked to specific version https://github.com/zeit/next-plugins/blob/8d58b4147e37f081ff76058dc8be9f4e29c1c37c/packages/next-sass/package.json#L8 so there is no possibility to make any mistake with `yarn upgrade` and that is that point.
If `next-css/css-loader-config` will change then `next-sass` will require different version compatible with that.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
