### ISSUE TITLE
next-css performance issue with react-dates

### ISSUE THREAD

**Issue by thian4** [vercel/next-plugins#383]
I'm not sure which side is causing the issue, when the first load and user clicked on the input, there will be slightly lag, check this out https://codesandbox.io/s/github/thian4/react-dates-nextjs

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
