### ISSUE TITLE
next-css breaks on data:image/svg+xml URLs

### ISSUE THREAD

**Issue by jaydenseric** [vercel/next-plugins#385]
3rd party CSS files from libraries such as `mapbox-gl` contain `data:image/svg+xml` URLs like this:

```.css
.foo {
  background-image: url("data:image/svg+xml;charset=utf-8,%3Csvg viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'%3E %3Cpath fill='%23333333' fill-rule='evenodd' d='M4,10a6,6 0 1,0 12,0a6,6 0 1,0 -12,0 M9,7a1,1 0 1,0 2,0a1,1 0 1,0 -2,0 M9,10a1,1 0 1,1 2,0l0,3a1,1 0 1,1 -2,0'/%3E %3C/svg%3E");
}
```

With the most basic installation of `next-css`, and pages with this import at the top:

```js
import 'mapbox-gl/dist/mapbox-gl.css'
```

You can visit the page ok by directly visiting the URL in the browser (SSR), but client side route navigations to the page get stuck forever in loading state, and the page never transitions. No error appears in console.

This is particularly problematic because trying to load the 3rd party CSS the `styled-jsx` way is also broken, [due to a stylis bug](https://github.com/zeit/styled-jsx/issues/500#issuecomment-451815832). Using `next/head` to import the CSS via a stylesheet link from CDN loads too slow, causing the library to emit a warning. I'm running out of options!

Versions:

- `@zeit/next-css@1.0.1`
- `next@8.0.0-canary.10`

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
