### ISSUE TITLE
Shouldn't next-sass and node-sass be dev dependencies in documentation?

### ISSUE THREAD

**Issue by TowhidKashem** [vercel/next-plugins#394]
In the documentation is shows to install `@zeit/next-sass` and `node-sass` as dependencies but shouldn't these be dev dependencies since the compilation should only be needed during development and on production the built CSS files will be served?

https://github.com/zeit/next-plugins/tree/master/packages/next-sass

**Comment by jibin2706** [comment]
So it should be dev dependency correct?
