### ISSUE TITLE
next-css: CSS files from a different URL are retained?

### ISSUE THREAD

**Issue by Ericxgao** [vercel/next-plugins#407]
I have imported two CSS files, alpha.css and beta.css in two different components Alpha and Beta, respectively. These components are on two different paths on my server, /alpha and /beta.
Let's say alpha.css and beta.css both have the same class declaration:

````
// Alpha.css
.someClass {
color: red
}

// Beta.css
.someClass {
font-size: 24pt
}
````
If I restart the server and visit /alpha, all is well. The class is colored red, with no text size adjustments. However, once I visit /beta and return to /alpha, the class inherits the font-size. It looks like beta.css is being retained somehow when I go back to /alpha. 

Since the class names are the same, .someClass now is inheriting attributes from Beta. It looks like Webpack is not clearing these css files when I change URLs - is this intentional?

In my case, while I am on the url /landing with the landing page rendered, why do I still have access to /stream's component after I visited that page? Is Webpack supposed to be retaining CSS files from other parts of my site?

![image](https://user-images.githubusercontent.com/6610675/53074449-a7baea80-349f-11e9-9d35-cfe49c2b7d4b.png)

**Comment by ivanhuay** [comment]
i have the same problem

**Comment by kimorkim** [comment]
1++

**Comment by cixing** [comment]
me too

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
