### ISSUE TITLE
Next don't minify the files in production mode.

### ISSUE THREAD

**Issue by Whitefox98** [vercel/next-plugins#408]
Hi,

When i build my app, a big JS file keeps without minify with size arround 300kb. 

The same happens with SASS don't get minified when compile. I try this:

```
next.config.js
const withSass = require('@zeit/next-sass')
const withOptimizedImages = require('next-optimized-images');
const withTypescript = require('@zeit/next-typescript')
module.exports = withSass({minified:true},withOptimizedImages(withTypescript()))
```

.babelrc
```
{
    "presets": [
        "next/babel",
        "@zeit/next-typescript/babel",
    ]
}
```

What i can do for minify SASS and all of my javascript files without comments and full optimitzed?

**Comment by patrykmaron** [comment]
Any luck?

**Comment by hyphmongo** [comment]
Having the same issue. The output css file has comments at the top of the file whereas I would expect them to be removed (along with white space)

**Comment by dijs** [comment]
I am also seeing this issue. Any thoughts here?

**Comment by seanplwong** [comment]
This would minify the output css

```js
module.export = {
  sassLoaderOptions: {
    outputStyle: 'compressed',
  },
}
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
