### ISSUE TITLE
ModuleParseError when importing scss/sass file from node_modules

### ISSUE THREAD

**Issue by azcn2503** [vercel/next-plugins#410]
I am able to `import "./index.scss";` without any problem. It compiles the page on load and I can see the styles are working.

When I try to import: `import "some-external-package/styles/index.scss";` from my index.js, or if I use an `@import` to the external package in the index.scss, I get the following error on loading the page:

```
./node_modules/some-external-package/styles/index.scss
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
```

This would seem to indicate that the .scss files are not being picked up by a loader, presumably because there is a default exclude rule that omits files from node_modules? Just my guess, but something that I have seen a number of times in other projects.

I have tried a few things (using next-sass plugin, using extracted-loader with ExtractTextPlugin, but that's definitely a no-go!) and unfortunately none so far have worked. My current strategy is on creating a custom webpack configuration in my `next.config.js` but I am not having any luck here so far. Here is the config right now:

```
const path = require("path");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

const cssLoaderConfigModules = {
  loader: "css-loader",
  options: {
    sourceMap: true,
    importLoaders: 1,
    modules: true,
    localIdentName: "[name]__[local]___[hash:base64:5]"
  }
};

const sassLoaderConfig = {
  loader: "sass-loader",
  options: {
    sourceMap: true,
    includePaths: [path.resolve(__dirname, "node_modules")]
  }
};

module.exports = {
  webpack: (config, { buildId, dev }) => {
    config.module.rules.push({
      test: /\.((sa|sc|c)ss|jpg|png)$/,
      use: [
        {
          loader: "emit-file-loader",
          options: {
            name: "dist/[path][name].[ext]"
          }
        }
      ]
    });

    config.module.rules.push({
      test: /\.(sa|sc|c)ss$/,
      exclude: /node_modules\/(?!some-external-package)/, // note that I am trying to include my package containing scss files here
      use: [
        {
          loader: "babel-loader"
        },
        {
          loader: MiniCssExtractPlugin.loader
        },
        cssLoaderConfigModules,
        sassLoaderConfig
      ]
    });

    config.plugins.push(
      new MiniCssExtractPlugin({
        // note: not sure if this is the correct output, will this conflict with anything next is doing?
        filename: dev
          ? path.join(__dirname, ".static/assets/index.css")
          : ".static/assets/" + buildId + ".css",
        allChunks: true
      })
    );

    return config;
  }
};

```

I am using MacOS Mojave with the following package versions:

```
  "dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "file-loader": "^3.0.1",
    "mini-css-extract-plugin": "^0.5.0",
    "next": "^8.0.3",
    "node-sass": "^4.11.0",
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
  },
```

The use case I am presented with is interesting - we would like to create a static site using our existing styles and React components that are already being used in a number of dynamic/non-static apps. Those apps also use webpack, though on version 2 instead of version 4, so copying and pasting configs will not work. Importing these SCSS styles is the first step to allowing those components to render nicely.

**Comment by azcn2503** [comment]
I have been able to get scss files loading using `@zeit/next-sass`, but it fails to load fonts unfortunately. 

I have tried to use `next-fonts` to facilitate the loading of fonts, but I believe the error happens before this point.

The error I am receiving is this:

```
Failed to compile.

./node_modules/react-component-library/styles/index.scss
ModuleNotFoundError: Module not found: Error: Can't resolve './react-component-library/fonts/icomoon/micons/fonts/icomoon.eot' in '/Users/aington/git/static-help-next/node_modules/react-component-library/styles'

> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/Users/aington/git/static-help-next/node_modules/next/dist/build/index.js:101:15)
    at <anonymous>
```

The error is not a good indicator of where the problem lies in my opinion, as there are no fonts being loaded by the file: `/Users/aington/git/static-help-next/node_modules/react-component-library/styles`. They are actually loaded in `/Users/aington/git/static-help-next/node_modules/react-component-library/styles/fonts.scss`, and the paths to the fonts look correct in this file. I triple checked just to make sure!

Here is the font definition it is failing on:

```
@font-face {
  font-family: 'icomoon';
  src: url(react-component-library/fonts/icomoon/micons/fonts/icomoon.eot);
  src: url(react-component-library/fonts/icomoon/micons/fonts/icomoon.eot?#iefix)
      format('embedded-opentype'),
    url(react-component-library/fonts/icomoon/micons/fonts/icomoon.ttf)
      format('truetype'),
    url(react-component-library/fonts/icomoon/micons/fonts/icomoon.woff)
      format('woff'),
    url(react-component-library/fonts/icomoon/micons/fonts/icomoon.svg#icomoon)
      format('svg');
  font-weight: normal;
  font-style: normal;
}
```

The fonts definitely exist in this location:

```
ls -l ~/git/static-help-next/node_modules/react-component-library/fonts/icomoon/micons/fonts/
total 1024
-rwxr-xr-x  1 aington  aington   80256 16 Nov 10:02 icomoon.eot
-rwxr-xr-x  1 aington  aington  277474 16 Nov 10:02 icomoon.svg
-rwxr-xr-x  1 aington  aington   80092 16 Nov 10:02 icomoon.ttf
-rwxr-xr-x  1 aington  aington   80168 16 Nov 10:02 icomoon.woff
```

(static-help-next is the name of my app).

Any help would be appreciated 👍

**Comment by popuguytheparrot** [comment]
Currently, it is better to use css in js (SC) solutions than standard writing styles.

Nextjs and next-plugins broken and cannot work with styles correctly

**Comment by chrisdrackett** [comment]
@popuguytheparrot sometimes that isn't an option depending on project requirements. I would love to stick with css-in-js, but can't in my case.

**Comment by sesteva** [comment]
+1 same exact problem with an external css stylesheet and fonts.

**Comment by KenZhouGreat** [comment]
I have the same issue with the Fontawsome SASS files. My finding was that there is some problem with the loading of "string interpolation" syntax i.e. "#{}". I still has not found any solid solution for the moment so I will have to include a cdn solution for the moment which really not should be the case.

Hope some one look into this issue and make a nextjs a better framework.

**Comment by geochanto** [comment]
running into the same issue. Any help would be appreciated.

**Comment by geochanto** [comment]
I was running into this and found out it was because I was calling fonts in @font-face which were not in my `/static` folder. Make sure fonts are placed inside `/static`, and then you can call them in your scss with an absolute path like `src: url('/static/some_subpath/some_font_example.eot');`

**Comment by snowgy920** [comment]
I also have the same issue. Did anyone solve this issue?

**Comment by janbiasi** [comment]
Any updates on this?

**Comment by snowgy920** [comment]
Not yet,
I decided not to use Next on current project.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by haotangio** [comment]
Anyone found the solution to fix this issue?

**Comment by bryandowning** [comment]
Check out the css-loader options (particularly `import` and `url`): https://github.com/webpack-contrib/css-loader#options There's info in there about importing from node_modules.

I was having module resolution errors with `url()` from a scss file when doing a static export, so I just turned off url resolution in css-loader.

```
module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]-[hash:base64:5]',
    url: false, // This fixed my problem
  },
})
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
