### ISSUE TITLE
Master branch currently contains older version numbers of packages

### ISSUE THREAD

**Issue by elliottsj** [vercel/next-plugins#417]
I noticed that the master branch of this repo has reverted to older version numbers of packages `next-css`, `next-less`, `next-mdx`, `next-sass`, and `next-stylus`, as of this commit: https://github.com/zeit/next-plugins/commit/12cd9d28905b63a1b90848f3e494dc3fb7465224

@timneutkens I couldn't find any release notes describing why this change was made, so I'm thinking this was an accidental `git merge`?

**Comment by timneutkens** [comment]
Hey! We're deprecating this repository. I just updated the readme. Thanks!
