### ISSUE TITLE
next-sass is not reporting building errors

### ISSUE THREAD

**Issue by devniel** [vercel/next-plugins#419]
Hi, I'm using this statement in my sass file 
`@import '../node_modules/@ibm/plex/scss/ibm-plex.scss';`

To handle this in a _non-next_ environment I did some webpack configurations based on errors that the sass loader or webpack reported, the problem is that with `next` the only thing that I receive is `Compiling ...`. Is there some argument that could print the webpack logs in this case ?.

Thanks

**Comment by YuraKostin** [comment]
Hello, i've got the similar issue.

I'm trying to move react application from old build tools to next.js.
First time i saw `You may need an appropriate loader to handle this file type.` in the terminal.

So, i've added next.config.js file with the next content:
```
const withSass = require('@zeit/next-sass');

module.exports = withSass({
    cssModules: true
});
```

And now i see just `Compiling...` and nothing more.

Is there any idea, how to solve it?

**Comment by asherccohen** [comment]
I would like to reopen this issue as I'm having the same problem with next 8.5.0. 
I'm running next in a monorepo using nx dev by nrwl.
The scss files I'm compiling come using a template (html5up) and I'm following this example https://github.com/codebushi/nextjs-starter-dimension.

My project is in Typescript.
I have all dependencies installed and tried adding next.config.js and postcss.config.js but the compiler just shows the `Compiling ...` message and no css is written to the output folder.

**Comment by asherccohen** [comment]
I have created this repo to show how this is affecting compilation:
[https://github.com/asherccohen/next-starter](url)

**Comment by asherccohen** [comment]
SOLUTION FOUND:
For anyone having the 'Compiling...' problem check webpack loaders.
My problem was due to url imports in scss (background: url(/something.jpg) pointing to the wrong folders; the imports were silently failing and stopping compilation.
In my case just changing the path worked but I suggest looking into a custom configuration in next.config.js (if you don't have one refer to the docs and create one).

An example could be:

const withSass = require('@zeit/next-sass');
const withCSS = require("@zeit/next-css");
module.exports = withCSS(withSass({
   webpack (config, options) {
       config.module.rules.push({
           test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
           use: {
               loader: 'url-loader',
               options: {
                   limit: 100000
               }
           }
       });

       return config;
   }
}));

This DID NOT work for me, as explained my solution was to change path in the url imports.
Please address the silently failing bug as it can be very time consuming not knowing where to look at.

**Comment by asherccohen** [comment]
Worth mentioning that none of the configurations suggested in @next/sass docs helped in debugging this problem.

For example this (or any of the other suggested configs) never worked:
const withSass = require('@zeit/next-sass');

module.exports = withSass({
    cssModules: true
});

Also in my case I was using typescript and I suggest linking this issue with [How to add a next.config.js file to customise a Next.js app #1895](url) as creating a next.config.js file in a typescript project is not straightforward.

**Comment by bgashler1** [comment]
I also experienced this elusive silent failure. Compilation seems to happen forever, but really it's an incorrect URL in your SCSS file.

**Comment by asherccohen** [comment]
UPDATE:
I also figured that next/images can properly solve this issue without using other loaders.
Just install the plugin and fix your urls.

**Comment by brockklein** [comment]
> SOLUTION FOUND:
> For anyone having the 'Compiling...' problem check webpack loaders.
> My problem was due to url imports in scss (background: url(/something.jpg) pointing to the wrong folders; the imports were silently failing and stopping compilation.
> In my case just changing the path worked but I suggest looking into a custom configuration in next.config.js (if you don't have one refer to the docs and create one).
> 
> An example could be:
> 
> const withSass = require('@zeit/next-sass');
> const withCSS = require("@zeit/next-css");
> module.exports = withCSS(withSass({
> webpack (config, options) {
> config.module.rules.push({
> test: /.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
> use: {
> loader: 'url-loader',
> options: {
> limit: 100000
> }
> }
> });
> 
> ```
>    return config;
> ```
> 
> }
> }));
> 
> This DID NOT work for me, as explained my solution was to change path in the url imports.
> Please address the silently failing bug as it can be very time consuming not knowing where to look at.

Wow, lifesaver @asherccohen. I was wondering why the heck my CRA imported SCSS was taken eons to compile. Found your comment, tested commenting out a `url()` import and, voila, as advertised everything compiled like a charm. Thanks for suggesting [next/image](https://www.npmjs.com/package/next-images) as well.

**Comment by asherccohen** [comment]
Well, glad it helped. It bugged me for enough time to understand your sufference 🤣

**Comment by j-holub** [comment]
I kind of have the same problem. When my SASS is faulty NextJs just used the latest working version before the errors, doesn't show any error.

I have seen the solution here in the thread, however I am not even using Webpack like this and I don't want to introduce so much more. My `next.config.js?` is just

```
const withSass = require('@zeit/next-sass');
module.exports = withSass()
```

**Comment by devniel** [comment]
Tried again these days and now it's reporting something 😁, BUT this time I'm not using next-sass, it seems that now Nextjs is using postcss by default at it also compiles sass.

```sh
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
Warning: A null PostCSS plugin was provided. This entry will be ignored.
Warning: A null PostCSS plugin was provided. This entry will be ignored.
> Using external babel configuration
> Location: "C:\example\.babelrc"
[ error ] ./styles/index.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??__nextjs_postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/next/node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./styles/index.scss)
Module not found: Can't resolve '../node_modules/@ibm/plex/scss/mono/bold/italic/node_modules/@ibm/plex/IBM-Plex-Mono/fonts/complete/woff/IBMPlexMono-BoldItalic.woff' in 'C:\example\styles'
[ wait ]  compiling ...
```

Also, just in case, it seems that when using _next-sass_ and setting it on the `next.config.js`, the `postcss.config.js` needs `require` for each module.

**Comment by kunal-thinlimbs** [comment]
my getStaticPath create problem when it has more than 500 dynamic pages

**Comment by asherccohen** [comment]
https://twitter.com/timer150/status/1263689549898829829?s=19

Team is trying to mak the experience with scss better, follow the thread as I suggested to look into compiling issues too.

**Comment by kunal-thinlimbs** [comment]
● /                           400 B          64.4 kB
├   /_app                       269 B          57.4 kB
├ ○ /404                        2.61 kB          60 kB
├ ● /players                    621 B          64.6 kB
└ ● /players/[id]               370 B          64.3 kB
    ├ /players/59547
    ├ /players/64390
    ├ /players/64769
    └ [+297 more paths]

it works fine if static site generator data length is less than 300 if it has 8K data or array it generate error

**Comment by umucorn** [comment]
I'm having the same problem, there is not one single sass error output. I try to solve it by looking at individual files and commenting / uncommenting their import statements. Ruby sass cli compiles it and outputs a css file totally fine. Next is not compiling and I can't open anything in browser.

**Comment by umucorn** [comment]
How to close this `url` checking behavior? I don't need it, it's not helping. Because I can't comment them out, not adding url loader worked at all.

**Comment by umucorn** [comment]
I just found out hese url loading problems don't exist in of Next 7, it loads images in those urls

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
