### ISSUE TITLE
TypeError: Cannot read property 'local' of undefined 

### ISSUE THREAD

**Issue by bhavikji** [vercel/next-plugins#421]
Hello folks, I am working on nextjs via create-next-app for the layout I am using ant design, where I need to import it from node_modules. I have tried initially dangerouslySetInnerHTML like this
 `<style dangerouslySetInnerHTML={{ __html: stylesheet }} />`
but I know that's not a right way to call 3rd party libraries from node_modules

Later I tried to import with using `@zeit/next-css` but it is throwing me this error

`TypeError: Cannot read property 'local' of undefined`

I try to dig deeper and found, with  `@zeit/next-css` we can't import 3rd parties dependencies, so alternatively I tried to import via 
`<link href="https://cdnjs.cloudflare.com/ajax/libs/antd/3.13.6/antd.css" rel="stylesheet"/>` but I am getting weird response sometimes scripts doesn't load properly and I am not getting any errors in console.
I need to know what is the best way or preferred way to call 3rd party libraries in next js?

**Comment by lwyj123** [comment]
Same here.

**Comment by daviddang91** [comment]
Same here

**Comment by jojonarte** [comment]
same here

**Comment by ZerdoX-x** [comment]
Bump. Same

**Comment by ZerdoX-x** [comment]
Solution: remove next-css
This worked for me. If you still have troubles, maybe because of Babel, try to configure it.
I haven't configured Babel in Next.js and have no troubles

Code below works fine for me
```
@import url('../../node_modules/nprogress/nprogress.css');
@import url('../../node_modules/antd/dist/antd.min.css');
```

P.S. You still can use CSS Modules out of the box as it was added in Next 9.2
https://nextjs.org/blog/next-9-2

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
