### ISSUE TITLE
Not working with next 6 & next 7...

### ISSUE THREAD

**Issue by CYB3RL1F3** [vercel/next-plugins#422]
# Bug report
Impossible to load style from node_module react-slick.

## Describe the bug

Receive this message : 
```
Module build failed (from app/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

## To Reproduce
apply next.config.js like following : 

```
module.exports = withCss(withTypescript({
    distDir: '../dist',
}));
```

Also tried : 

```
const wcss = withCss({
    server: true
});

module.exports = withTypescript({
    distDir: '../dist',
    ...wcss
});
```

I tried options like modules, etc...
The CSS file is loaded from a node_module.
Important : we are in a lerna context. The component using the css is in UI and called from main-app. The typescript is configured in UI (that's why there is only distDir in the typescript options).

Steps to reproduce the behavior, please provide code snippets or a repository:
with next 7.0.0 and next-css 1.0.0

## System information
 - Version of Next.js: [e.g. 7.0.0]

**Comment by GeorgeBellTMH** [comment]
```
if (typeof require !== "undefined") {
    require.extensions[".less"] = () => {};
    require.extensions[".css"] = (file) => {};
} 
```

Works for me when running in dev, but does not work when running next export...

**Comment by ruxandrafed** [comment]
@GeorgeBellTMH I'm having the same problem. Have you discovered a fix by any chance? I have been trying all sorts of things..

**Comment by kachkaev** [comment]
@GeorgeBellTMH @ruxandrafed I struggled with the same problem in `ant-design` less files. The solution came when I looked into [next.js → examples → with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less). Replacing `if (typeof require !== "undefined") {...` with the hack they have in [`next.config.js`](https://github.com/zeit/next.js/blob/canary/examples/with-ant-design-less/next.config.js) made it possible to `yarn build && yarn export`. I don't understand what's going on there, just know that the trick works 😅

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
