### ISSUE TITLE
autoprefixer not working with nextjs7?

### ISSUE THREAD

**Issue by WEN-JY** [vercel/next-plugins#423]
I met this problem recently when I add postcss.config.js to the root dir of my project,the content of my config is just like this:
```
const autoprefixer = require('autoprefixer');
module.exports = {
    plugins: [
        autoprefixer({
            browsers: [ '>1%',
                'last 4 versions',
                'ios >= 6',
                'not ie < 9']
        })
    ]
};
```

I‘ve installed this npm package autoprefixer by 'yarn add autoprefixer'.and I also add a 'browserslist' option in my package.json.but nothing chaned after starting my project ,the css is just what it was before.

![image](https://user-images.githubusercontent.com/36290410/53854805-de4b4600-4005-11e9-8c19-09ae9e24a3f6.png)
anyone konws how to get it work ?thx a lot.

**Comment by OndeVai** [comment]
Is your postcss.config.js actually running? I ran a similar config thru next-sass plugin, but next-css should work too.

**Comment by radeno** [comment]
@WEN-JY try to setup `browserList` into package.json. One shot two hits. It is same for `babel-env` and `autoprefixer`

For example ours settings:
```
  "browserslist": [
    ">= 0.5%",
    "chrome >= 42",
    "and_chr >= 42",
    "and_ff >= 38",
    "android >= 4.4",
    "edge >= 12",
    "firefox >= 38",
    "ie >= 11",
    "ios_saf >= 9",
    "safari >= 9",
    "node 10"
  ]
```

**Comment by KB1RMA** [comment]
Plugins takes an object rather than an array. Switch it to something like this:

```js
const autoprefixer = require('autoprefixer');
module.exports = {
    plugins: {
        autoprefixer({
            browsers: [ '>1%',
                'last 4 versions',
                'ios >= 6',
                'not ie < 9']
        })
    }
};
```

And you'll probably be all set.

**Comment by Liroo** [comment]
> Plugins takes an object rather than an array. Switch it to something like this:
> 
> ```js
> const autoprefixer = require('autoprefixer');
> module.exports = {
>     plugins: {
>         autoprefixer({
>             browsers: [ '>1%',
>                 'last 4 versions',
>                 'ios >= 6',
>                 'not ie < 9']
>         })
>     }
> };
> ```
> 
> And you'll probably be all set.

This has no sense, what's the key of `autoprefixer` function in the object ? An object is a combinaison of key/value and there is only a value here.

**Comment by alvinthen** [comment]
> This has no sense, what's the key of `autoprefixer` function in the object ? An object is a combinaison of key/value and there is only a value here.

It's an ES2015 feature, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
