### ISSUE TITLE
SourceMapDevToolPlugin does not work - ignored

### ISSUE THREAD

**Issue by zelphir** [vercel/next-plugins#426]
After https://github.com/zeit/next-plugins/pull/350 (using `optimize-css-assets-webpack-plugin` to minify css files), `webpack.SourceMapDevToolPlugin` is ignored (https://github.com/NMFR/optimize-css-assets-webpack-plugin/issues/99), that means that is not possible to create custom sourcemaps for CSS files

**Comment by zelphir** [comment]
workaround:

in `webpack` config:

```js
    const filteredMinimizers = config.optimization.minimizer.filter(
      (plugin) => plugin.constructor.name !== 'OptimizeCssAssetsWebpackPlugin'
    );
    config.optimization.minimizer = filteredMinimizers;
```

And use `postcss` to minify css files.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
