### ISSUE TITLE
Next-sass  does not raise an exception when including scss into _document.js

### ISSUE THREAD

**Issue by ryanolee** [vercel/next-plugins#435]
Extension of https://github.com/zeit/next-plugins/pull/331 this issue has also cropped up when using next-sass as the compiled css is not included into the bundled files either.

This issue might also present itself in other modules that compile the resulting import into css. I have only experienced this with `next-sass` thus far.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
