### ISSUE TITLE
Css compression does not work

### ISSUE THREAD

**Issue by kodermax** [vercel/next-plugins#443]
When i use next-css, minify css not working on the production.

**Comment by robeno** [comment]
I have the same problem. No big settings in next.config.js
I also don't see any option in documentation for css minification.

```
// next.config.js
const withPlugins = require('next-compose-plugins');
const withFonts = require('next-fonts');
const withSass = require('@zeit/next-sass');
const withTypescript = require('@zeit/next-typescript');
const getRoutes = require('./routes');
const withSize = require('next-size');

const nextjsoptions = {
  useFileSystemPublicRoutes: false,
  exportPathMap: getRoutes
}

module.exports = withPlugins([
  withFonts,
  withSass,
  withSize,
  withTypescript
],  nextjsoptions)
```

**Comment by MiDouShiTongTong** [comment]
[This answer works for me](https://spectrum.chat/next-js/general/production-build-css-files-are-not-minified~9f9f43b8-ec8b-45e5-a8e3-5b57a62e9e67?m=MTU0MTA5MDQ1Nzk1Mw==)

**Comment by chase** [comment]
@kodermax @robeno @MiDouShiTongTong 
This was fixed in one of the canary versions. I'm not sure why it isn't being released on the stable version.

Use `npm install --save @zeit/next-css@0.2.1-canary.4`

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
