### ISSUE TITLE
next-less with typescript, css modules & typings-for-css-modules-loader

### ISSUE THREAD

**Issue by visuallization** [vercel/next-plugins#459]
Hi guys!

Thank you for your framework!

I have a question. I am a fan on using typescript and less in my projects.
To have the whole typescript experience I also use typings for my less files.
Usually I generate them automatically with typings-for-css-modules-loader https://www.npmjs.com/package/typings-for-css-modules-loader.

What would be the best way to have auto generadted style defintitons for next-less and typescript? Is there already a preferenced way or should I just fork the next-less plugin and make it work?

Cheers and thank you for your support!

**Comment by visuallization** [comment]
If anyone comes across this.
I found a way to make it work.

Here is my next.config.js:

```
const withLess = require('@zeit/next-less');
const withTypescript = require('@zeit/next-typescript');

module.exports = withTypescript(
  withLess({
    cssModules: true,
    cssLoaderOptions: {
      importLoaders: 1,
      localIdentName: "[local]___[hash:base64:5]",
    },
    distDir: '../.next',
    webpack: (cfg) => {
      cfg.module.rules.push(
          {
              test: /\.md$/,
              use: 'frontmatter-markdown-loader'
          }
      );

      if (cfg.mode === 'development' && cfg.name === 'client') {
        cfg.module.rules[2].use[2].loader = require.resolve('typings-for-css-modules-loader');
        cfg.module.rules[2].use[2].options.namedExport = true;
        cfg.module.rules[2].use[2].options.camelCase = true;
      }

      return cfg;
    }
  })
);
```

It is not the most beautiful solution as the indexes are hardcoded and might have to be updated when something changes in the config or if you update a next module, but it works out of the box with standard next-less and next-typescript which is fine for me for now. :)

Cheers

**Comment by Lemaro86** [comment]
But what about it? 

@zeit/next-typescript is no longer needed since Next.js has built-in support for TypeScript now. Please remove it from your next.config.js and your .babelrc
