### ISSUE TITLE
I cant upload SCSS files

### ISSUE THREAD

**Issue by cabralada** [vercel/next-plugins#460]
Error to import **scss**

![1](https://user-images.githubusercontent.com/1890957/57201482-be9ab480-6f99-11e9-86fe-4eeafa1677af.PNG)
![2](https://user-images.githubusercontent.com/1890957/57201483-be9ab480-6f99-11e9-9b73-09586c0efd7d.PNG)

```
[ error ] ./pages/App.scss 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

```

### next.config.js
```
const withSass = require('@zeit/next-sass')
module.exports = withSass()
```

### package.json
```
{
  "dependencies": {
    "@material-ui/core": "^3.9.2",
    "@material-ui/icons": "^3.0.2",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "axios": "^0.18.0",
    "classnames": "^2.2.6",
    "next": "^8.1.0",
    "node-sass": "^4.12.0",
    "normalize.css": "^8.0.1",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-infinite-scroller": "^1.2.4",
    "redux": "^4.0.1",
    "rxjs": "^6.4.0"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  }
}

```

What is missing?

**Comment by tmohammad78** [comment]
I have your problem too , but I can't fix it , it looks right but i don't whats wrong

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
