### ISSUE TITLE
Have you tried that solution? https://github.com/akiran/react-slick/issues/842#issuecomment-385378629

### ISSUE THREAD

**Issue by Mhmdabed11** [vercel/next-plugins#464]
Have you tried that solution? https://github.com/akiran/react-slick/issues/842#issuecomment-385378629
```
# Install dependencies
yarn add --dev @zeit/next-css file-loader url-loader
```
```js
// next.config.js
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    })
    return config
  }
```
how can i add `cssModules:true` in this case ?

_Originally posted by @Purii in https://github.com/zeit/next-plugins/issues/273#issuecomment-430597241_

**Comment by vinzun** [comment]
```javascript
const withCSS = require('@zeit/next-css');
//install next-compose-plugins
const withPlugins = require('next-compose-plugins');

const nextConfig = {

  webpack: function(config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    });
    return config;
  }
};

module.exports = withPlugins([withCSS], nextConfig);
```

**Comment by vinzun** [comment]
```javascript
const withCSS = require('@zeit/next-css');
//install next-compose-plugins
const withPlugins = require('next-compose-plugins');

const nextConfig = {
  webpack: function(config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        }
      }
    });
    return config;
  }
};

module.exports = withPlugins([withCSS, {cssModules: true}], nextConfig);
```

**Comment by sanderkooger** [comment]
@vincezun I tries your next.config but no joy. 

[ error ] ./node_modules/slick-carousel/slick/slick-theme.css
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
Could not find files for /index in .next/build-manifest.json
ModuleBuildError: Module build failed (from ./node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

**Comment by ciriussaini** [comment]
> @vincezun I tries your next.config but no joy.
> 
> [ error ] ./node_modules/slick-carousel/slick/slick-theme.css
> ValidationError: CSS Loader Invalid Options
> 
> options should NOT have additional properties
> Could not find files for /index in .next/build-manifest.json
> ModuleBuildError: Module build failed (from ./node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
> ValidationError: CSS Loader Invalid Options
> 
> options should NOT have additional properties

Did you find any solution to this ??
I am getting same problemm

**Comment by hmzaabasi** [comment]
> > @vincezun I tries your next.config but no joy.
> > [ error ] ./node_modules/slick-carousel/slick/slick-theme.css
> > ValidationError: CSS Loader Invalid Options
> > options should NOT have additional properties
> > Could not find files for /index in .next/build-manifest.json
> > ModuleBuildError: Module build failed (from ./node_modules/@zeit/next-css/node_modules/mini-css-extract-plugin/dist/loader.js):
> > ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
> > ValidationError: CSS Loader Invalid Options
> > options should NOT have additional properties
> 
> Did you find any solution to this ??
> I am getting same problemm

Any Solution you found ?

**Comment by sanderkooger** [comment]
No real sollution found. But something weird. 

If i use the Dockerfile in the with-docker example it builds well. 

If i change the dockerfile to not build and run as root user it fails. . 

Workarround for now is work with this Dockerfile
```
# Do the npm install or yarn install in the full image
FROM mhart/alpine-node:12 AS builder
#27 Try to run and build as node user. sollution not working Server starts but fails to serve. 
# RUN addgroup -g 1001 -S www-data && \
#     adduser -u 1001 -S www-data -G www-data && \
#     mkdir /app && \
#     chown www-data:www-data /app
# USER www-data
WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .
RUN yarn build && yarn test && yarn --production

# And then copy over node_modules, etc from that stage to the smaller base image that does no run the service as root. 
FROM mhart/alpine-node:slim-12
#27 Try to run and build as node user. sollution not working Server starts but fails to serve. 
# RUN addgroup -g 1001 -S www-data && \
#     adduser -u 1001 -S www-data -G www-data && \
#     mkdir /app && \
#     chown www-data:www-data /app
# USER www-data
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/server.js ./server.js
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
```
