### ISSUE TITLE
Add sideEffects to all style loaders

### ISSUE THREAD

**Issue by eashish93** [vercel/next-plugins#470]
I got into a problem where importing component from library like `material-components-web` doesn't load css in production.
This is because the library author marked the component as side effects free which remove css also from production.
So, suppose if I import snackbar component like this and then compile for production, the css will not included in production.
```js
  import {MDCSnackbar} from '@material/snackbar';
  import '@material/snackbar/dist/mdc.snackbar.css'; 

 // require('@material/snackbar/dist/mdc.snackbar.css');   // this will be imported because of old-style require.

  // ... some other react code ..
```
So, the solution is to add `sideEffects:true` in all loaders including sass, css, less etc.
Here's the open bug about this: https://github.com/webpack/webpack/issues/6571
and the implementation in `create-react-app` here:
https://github.com/facebook/create-react-app/blob/317f5002233029942394df9e87183420359b18cf/packages/react-scripts/config/webpack.config.js#L457

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
