### ISSUE TITLE
withSass seems to be broken

### ISSUE THREAD

**Issue by jhackett1** [vercel/next-plugins#471]
I've followed the install instructions for the sass plugin, created the first .scss and get a build error:

```
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
```

Something to do with CSS loader perhaps?

I've had to solve it by adding `"css-loader": "^1.0.1"` as an explicit dependency.

**Comment by abominab** [comment]
Getting this same exact error as well. My next.config.js is so:

```
module.exports = withSass({
	webpack(config) {
		config.plugins.push(new webpack.EnvironmentPlugin(localEnv));
		return config;
	}
});
```

**Comment by jordanoverbye** [comment]
I've got the same problem. Fixed with @jhackett1's answer.

```
"css-loader": "^1.0.1",
"next": "^9.0.0",
"node-sass": "^4.12.0"
```

**Comment by khatkarr** [comment]
Same error with css-loader:2.1.1:
```
ValidationError: CSS Loader Invalid Options
options should NOT have additional properties
```

**Comment by lucas-medina** [comment]
I guess current `css-loader@3.0.0` has some breaking changes related to how `withSass` uses its configuration. Setting `css-loader` version to `1.0.1` in my project has solved this issue for me. But I believe that new versions of next-sass should already bear that in mind :clap:

**Comment by heyuncoder** [comment]
I've got the same problem.  Setting css-loader version from 3.1.0 to 1.0.1 in my project has solved this issue for me. thanks @jhackett1

**Comment by cesarvarela** [comment]
Had the same problem downgrading `css-loader` fixed it

**Comment by gavinmeier25** [comment]
Has any resolution been made for this? Seems like setting it down is a temporary solution..

**Comment by marcin-piekarski** [comment]
Same as most of you. I had to downgrade my `css-loader` to 1.0.1 to get around the issue.

**Comment by botv** [comment]
Is it just me, or does this feel a little bit hacky?

**Comment by gavinmeier25** [comment]
I ended up fixing it without having to revert

**Comment by botv** [comment]
@gavinmeier25 how?

**Comment by gavinmeier25** [comment]
I realized I had css loader as a dependency on mistake bc I was integrating with storybook as well. Removing that fixed my problem

**Comment by botv** [comment]
Hmmm...not working for me.

I get hit with the `Module not found: Can't resolve 'css-loader'`

**Comment by mieradi** [comment]
> EDIT: I got mine working. I noticed my node_modules folder still had a next-css inside it though I had removed that from package.json. A delete of package-lock.json and node_modules got me running again and now I get scss files loading. Yay!
> 
> Getting this same exact error as well. My next.config.js is so:
> 
> ```
> module.exports = withSass({
> 	webpack(config) {
> 		config.plugins.push(new webpack.EnvironmentPlugin(localEnv));
> 		return config;
> 	}
> });
> ```

I didn't have next-css installed, but **removing package-lock.json** and **node_modules** did it for me.

**Comment by orenmizr** [comment]
@jordanoverbye can you elaborate ? i changed my package,json with that settings and clean installed it - still the same issue.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
