### ISSUE TITLE
Better and correct error messages 

### ISSUE THREAD

**Issue by nikandlv** [vercel/next-plugins#476]
When there's an issue compiling it won't spit out any error messages.

for example if we add an config like this

```javascript
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
    webpack: function (config) {
      config.module.rules.push({
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
            name: '[name].[ext]'
          }
        }
      })
      return config
    }})
```

and we have installed `@zeit/next-css` and forgot to install `file-loader` or 'url-loader' we will get

```
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ ready ] compiled successfully
[ info ]  ready on http://localhost:3000
[ event ] client pings, but there's no entry for page: /_error
[ event ] build page: /
[ wait ]  compiling ...
(node:15057) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 / listeners added. Use emitter.setMaxListeners() to increase limit

```

Or with sass plugin when we have relative URLs it just loops, never compiles and gives us no clue about wth is going on

we will get

```(node:15057) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 / listeners added. Use emitter.setMaxListeners() to increase limit```

or when we add a web font from node_modules with CSS plugin it won't import the module's local font and will give a syntax error! 

sorry about the toxication i just wasted alot time finding what the issue is

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
