### ISSUE TITLE
css and sass compilation error: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by laurencefass** [vercel/next-plugins#481]
I've followed the most basic installation procedure for next_css and next_sass. 

`Create a next.config.js in the root of your project (next to pages/ and package.json)

// next.config.js
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  /* config options here */
})
Create a CSS file style.css

.example {
  font-size: 50px;
}
Create a page file pages/index.js

import "../style.css"

export default () => <div className="example">Hello World!</div>
`

I'm getting the same compilation error for both.

```
Module parse failed: Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
> body {
|     border:2px solid red;
| }
```

im new to next.js so i dont know how to debug further but im happy to send further info if required.

thanks

**Comment by ChristopherLMiller** [comment]
There is a plugin for this however it's broken in that if you don't import your css in _document I think it is it will hang the rendering of the page.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
