### ISSUE TITLE
Bootstrap 4 with scss to working

### ISSUE THREAD

**Issue by JayU9769** [vercel/next-plugins#486]
I want to use bootstrap.scss within the project as cssModules bt when i import bootstrap.scss in component text-primary, text-align, etc.. class is not working

`

```
// next.config.js


const withSass = require('@zeit/next-sass');
module.exports = withSass({
    cssModules: true,
});
```

```

// Style.scss

@import '~bootstrap/scss/bootstrap';

$font-size: 50px;
.example {
  font-size: $font-size;
  color: #282828;
}

```

```

//index.js


import css from '../static/styles.scss';
const Index = () => (
    <div>
        `<h1 className={css.textPrimary}>Hello world</h1>`
    </div>
);

export default Index;
`
```
how can solve this I want to use bootstrap in a bundle with cssModules

**Comment by designbyadrian** [comment]
First, keep your scss files outside `static`, or they won't be transpiled.

Second, it's not possible to use Bootstrap as CSS module. I suggest loading it as global CSS in  _app.js, then you use bootstrap's global classes together with your modules:

```javascript
import css from './style.scss';
<div className={`btn btn-primary ${css.MyStyle}`} />
```

or with the [classnames](https://www.npmjs.com/package/classnames) package:

```javascript
import cx from 'classnames';
import css from './style.scss';
<div className={cx('btn btn-primary', css.MyStyle)} />
```

A discussion about how to implement global styles can be found here: https://github.com/zeit/next-plugins/issues/149

**Comment by findela** [comment]
I have no luck how to compile my sass/scss files to a single css file with @Zeit/next-sass package. Trying this for a long day. Any help as I want to include css to my layout not the sass/scss file.

`const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
module.exports = withCSS(withSass(
    {
        cssModules: true,
        cssLoaderOptions: {
            importLoaders: 1,
            localIdentName: "[local]___[hash:base64:5]",
        }
    }
));
module.exports.useFileSystemPublicRoutes = false;
`

Here is my trying code snippet.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
