### ISSUE TITLE
withSass in dev sometimes don't load page styles

### ISSUE THREAD

**Issue by aralroca** [vercel/next-plugins#491]
I'm not sure why is this happening but I guess that is not normal.

Using withSass plugin, navigating throw my app `localhost:3000` (in dev), sometimes the app gets frozen for a moment, and just after that, the styles of the page that I'm navigating into, are not loaded. So I need to refresh the page to load the styles of this page (with SSR always the styles are loaded correctly). 

At least this is not happening in production, but I don't feel very comfortable with this in dev environment.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
