### ISSUE TITLE
Custom attributes to the <link> generated by next-sass

### ISSUE THREAD

**Issue by amitschandillia** [vercel/next-plugins#494]
I'm currently using **next-sass** to process a Sass stylesheet and embed a link to it as:

`<link rel="stylesheet" href="/_next/static/css/styles.3bbc081a.chunk.css">
`

However, I would like the `rel` attribute to read something else, say, `preload` instead. Also, I would like to add a couple of custom attributes, such as `as=style` and `crossorigin`.  Is there any way I could make that happen using `next-sass` along with any third-party module if necessary?

**Comment by hungnguyen1995** [comment]
metoo

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
