### ISSUE TITLE
Change default css extension to .pcss

### ISSUE THREAD

**Issue by equinusocio** [vercel/next-plugins#501]
I'm using postcss and i want to set `.pcss` as css extension since is the default extension and allow the ide to associate the correct syntax. I can't find any guide to set the extension, any tips?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
