### ISSUE TITLE
<Link> click lose the css in dev mode

### ISSUE THREAD

**Issue by icai** [vercel/next-plugins#503]
# Bug report

## Describe the bug

in `A` page 

```
import "@styles/index.less";
```

in `Index` page

```jsx
<Link href={a.path} key={route.category + a.label}>
    <a className="item">
        {a.label}
    </a>
</Link>
```

If I click  the `Link` in `Index` page  navigate to `A` Page. the styles lose in dev mode(DemandEntry build complete).

but If I refresh the `A` Page, the style is OK.

the `next.config.js` is  the following:

```js
withCSS(withLess(withFonts(withTypescript(config))));

```

the styles final find in 
`<link rel="stylesheet" href="/_next/static/css/styles.chunk.css">`

## I think

may be caused by `onDemandEntryHandler`, I am not sure this

or need the hash update 

```
<link rel="stylesheet" href="/_next/static/css/styles.chunk.css?needupdate">
```

## System information

- OS: macOS
- Browser Chrome
- Version of Next.js:  "^8.1.0", ^9.0.2

**Comment by icai** [comment]
maybe have some relationship with this issue https://github.com/zeit/next.js/issues/8124

**Comment by calvinchankf** [comment]
i got the same problem

**Comment by ghostTing** [comment]
I have the same problem

**Comment by nuanyang233** [comment]
I have similar issue.
I was using `@nextjs9.0` and `@next/less`.
except `<Link>`, the `Router.push` will cause same problem.

**Comment by aralroca** [comment]
Same problem with `with-sass` plugin.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
