### ISSUE TITLE
Anyone interested in a Modernizr plugin?

### ISSUE THREAD

**Issue by scottydev** [vercel/next-plugins#504]
Would love to see Modernizr officially supported. I'll look into whipping up a plugin. Any input for official vs community supported?

**Comment by scottydev** [comment]
Got it working here:
https://www.npmjs.com/package/next-plugin-modernizr

Will fine tune the docs in a bit

**Comment by timneutkens** [comment]
Hey! We're deprecating this repository so I'm closing this issue.
