### ISSUE TITLE
Should we have next-ant-design plugin?

### ISSUE THREAD

**Issue by phakphumi** [vercel/next-plugins#507]
In normal case, we can use [with-ant-design-less](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less) or [with-ant-design](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design) to be the solution.

Anyway, there is some case that the developer wants to enable cssModule feature. Unfortunately, enable cssModule feature cause breaking all ant design style.

After taking time to research I can compose the solution [here](https://github.com/zeit/next.js/issues/8156#issuecomment-516009764).

I expect that Next will have an official plugin to help any developer work on this issue. It may be a common issue in the future.
So, what do you guy think? should it be a new plugin?

**Comment by dpyzo0o** [comment]
Any updates on this issue?

**Comment by 7mllm7** [comment]
+1

**Comment by ionpetro** [comment]
+1
