### ISSUE TITLE
[next-css] Unmet peer dependencies

### ISSUE THREAD

**Issue by pikeas** [vercel/next-plugins#515]
Package.json dependencies:

```
"dependencies": {
  "@zeit/next-css": "^1.0.1",
  "next": "^9.0.3",
  "react": "^16.9.0",
  "react-dom": "^16.9.0"
}
```

From a clean start, no `node_modules` and no `yarn.lock`:

```
$ yarn
yarn install v1.17.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@zeit/next-css > css-loader@1.0.0" has unmet peer dependency "webpack@^4.0.0".
warning "@zeit/next-css > mini-css-extract-plugin@0.4.3" has unmet peer dependency "webpack@^4.4.0".
```

NextJS seems to be working, but it would be nice to clean up these warnings.

**Comment by MoritzKn** [comment]
You can just add `webpack` to your dependencies and the warning will disappear. This should be a fine solution but maybe there is a better way?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
