### ISSUE TITLE
next-less is using less-loader@4.1.0

### ISSUE THREAD

**Issue by ganlub** [vercel/next-plugins#518]
With the latest version of less (3.10.0) my builds are breaking. 
I found this related issue at the less repo: https://github.com/less/less.js/issues/3414

I had to fix less to version 3.9.0 for it to keep building.

**Comment by buerxixi** [comment]
Yes 3.10.0 is breaking update. you loader must be upgrade 5.0.0.

**Comment by buerxixi** [comment]
> With the latest version of less (3.10.0) my builds are breaking.
> I found this related issue at the less repo: [less/less.js#3414](https://github.com/less/less.js/issues/3414)
> 
> I had to fix less to version 3.9.0 for it to keep building.

Yes 3.10.0 is breaking update. you loader must be upgrade 5.0.0.
