### ISSUE TITLE
error in use

### ISSUE THREAD

**Issue by AprinDev** [vercel/next-plugins#528]
hi
i want to use from next-css
by in next.config.js when i was using  next-css i got the below message 

Could not find a declaration file for module '@zeit/next-css'. 'e:/hamed/next-js/node_modules/@zeit/next-css/index.js' implicitly has an 'any' type.
  Try `npm install @types/zeit__next-css` if it exists or add a new declaration (.d.ts) file containing `declare module '@zeit/next-css';`

My next-config.js :
const withCSS = require('@zeit/next-css')
module.exports = withCSS()

please help me . i need to import css files

**Comment by nawatend** [comment]
I have the same warning, but my css is working tho. have you **import css** file in your component?

**Comment by AprinDev** [comment]
> I have the same warning, but my css is working tho. have you **import css** file in your component?

yes , ofcourse ... but my app had app crash and said that style.css that i import was caused of crash

i'm so confuse :(

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
