### ISSUE TITLE
Next JS | Webpack 4 | Webpack config to minify Stylus files on production 

### ISSUE THREAD

**Issue by milindvaityGH** [vercel/next-plugins#530]
Hello,

We have used Stylus in our next js app. and we wanna minify the CSS file that generates in the production build.
CSS chunks are getting generated, but files are not minified. 

We have use "mini-css-extract-plugin" 

Our code config 
-----------------------------------
    config.module.rules.push({
      test: /\.styl$/,
      use: [
        MiniCssExtractPlugin.loader,
        'css-loader',
        'stylus-loader'
      ],
    }, )
    config.plugins.push(
      new MiniCssExtractPlugin({
        filename: '[name][hash].css',
      }),new ManifestPlugin({
         fileName: 'custom-manifest.json'
    })
    )
-----------------------------------

We also try "minify-all" which we are using part of build script. But we are getting the following error 

.mdc-select--outlined .mdc-select__native-control,
^
ERROR: Unexpected token: punc (.)
    at JS_Parse_Error.get (eval at <anonymous> (D:\temp\node_modules\uglify-es\tools\node.js:21:1), <anonymous>:75:23)
    at fatal (D:\temp\node_modules\uglify-es\bin\uglifyjs:300:53)
    at run (D:\temp\node_modules\uglify-es\bin\uglifyjs:239:9)
    at Object.<anonymous> (D:\temp\node_modules\uglify-es\bin\uglifyjs:169:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

Is there any other options ??? please suggest.

**Comment by rlau1115** [comment]
+1

**Comment by rlau1115** [comment]
@milindvaityGH have you made any progress on this? Also dealing with the same issue.

**Comment by rlau1115** [comment]
To anyone else who might be struggling with this, seemed to have found a workaround:

```
const stylus = require('@zeit/next-stylus')
const optimizedImages = require('next-optimized-images');
const bundleAnalyzer = require('@next/bundle-analyzer')
const _ = require("underscore")
// documentation: https://www.npmjs.com/package/next-compose-plugins
const withPlugins = require('next-compose-plugins');
const nextConfig = {
    target: 'serverless',
    webpack: (config, options) => {
    // modify the `config` here
    // Logs
        // console.log("\n\n\n\nconfig", config)
        // console.log("\n\n\n\nconfig.module.rules", config.module.rules)
        // console.log("\n\n\n\noptions", options)
        // console.log("\n\n\n\nconfig.optimization", config.optimization)
        // console.log("\n\n\n\nconfig.mode", config.mode)
    // Minify stylus CSS
    if (config.mode === 'production') {
        /*
                config.module - rule { 
                    test: /\.styl$/,
                  use:
                   [ 'extracted-loader',
                     '/Users/noobs/Documents/DevProjects/vinyasa/website/node_modules/mini-css-extract-plugin/dist/loader.js',
                     { loader: 'css-loader', options: [Object] },
                     { loader: 'stylus-loader', options: {} } 
                   ] 
              }
        */
        _.each(config.module.rules, (rule) => {
            console.log("==================\nconfig.module - rule", rule)
            if ((_.find(rule.use, (use) => (use.loader && use.loader == 'stylus-loader')))) {
                console.log("match found, adding postcss-loader")
                // insert this loader right before stylus-loader.
                // splice -> loaders are processed last-to-first, so the postcss minification step happens right after the stylus-loader processes
                rule.use.splice(rule.use.length - 1, 0, {
                      loader: 'postcss-loader',
                      options: {
                        ident: 'postcss',
                        plugins: (loader) => [
                          require('cssnano')()
                        ]
                      }
                    })
            }
        })
      }
    return config;
  },
}
module.exports = withPlugins([
    optimizedImages,
    stylus,
    [bundleAnalyzer, {enabled: process.env.ANALYZE === 'true'}],
], nextConfig)
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
