### ISSUE TITLE
Why all style pack in one chunk??

### ISSUE THREAD

**Issue by didiself** [vercel/next-plugins#532]
I read @zeit/next-css source code, in css-loader-config.js 24-41 line. 
![image](https://user-images.githubusercontent.com/14201030/64579688-4fedbd80-d3b6-11e9-8ec4-00adf2abb4a3.png)
That code pack all pages style in one styles.css, but I want split css with page. 
So why do that??

**Comment by loljtdg** [comment]
I have the same question

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
