### ISSUE TITLE
Is it ok to upgrade css-loader to the latest version？

### ISSUE THREAD

**Issue by zyrepo** [vercel/next-plugins#533]
it not work 

![image](https://user-images.githubusercontent.com/22114645/64597216-e7b7cf80-d3e7-11e9-8174-f504495a945b.png)

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
