### ISSUE TITLE
[next-sass] Fail to refer styles using `import`

### ISSUE THREAD

**Issue by tleperou** [vercel/next-plugins#536]
Hi guys,

I follow the README to get into sass within an empty NextJS application.

Using `require` to get styles works, while `import` fails the compile as below:

```sh
Cannot find module './styles.scss'
```

Did I miss something?
The README is quite clear, though.

**Comment by moonformeli** [comment]
I was stuck in the same issue, I solved it with this solution.
Try add `typings` folder in the directory where `pages` is.
Make `declarations.d.ts` in `typings`.
```ts
declare module "*.scss" {
  const content: { [className: string]: string };
  export = content;
}
```

See [issue#91](https://github.com/zeit/next-plugins/issues/91)

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
