### ISSUE TITLE
Errors in Stylus/CSS/... builds leave dev environment stuck

### ISSUE THREAD

**Issue by akx** [vercel/next-plugins#539]
If a .css/.styl file has an error – in my case a problem resolving a relative path I hadn't changed while refitting an old site to Next.js – it'll cause the dev server to get stuck on "wait - compiling" and the browser will never navigate to the site (as the server never responds), like:

```
$ ./node_modules/.bin/next dev
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ event ] build page: /
[ wait ]  compiling ...
```

Running `next build` will expose the error though:
```
$ ./node_modules/.bin/next build
Failed to compile.

./styles/style.styl
ModuleNotFoundError: Module not found: Error: Can't resolve '../images/jumbo.jpg' in 'styles'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (node_modules/next/dist/build/index.js:7:847)
```

This smells like a promise error being dropped on the floor or similar. :)

Relevant package versions:

```
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-stylus": "^1.0.1",
    "next": "^9.0.6",
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
