### ISSUE TITLE
cssModules and Link/Router conflict

### ISSUE THREAD

**Issue by RuanXuSong** [vercel/next-plugins#542]
Hi,I find a problem while I'm using `cssModules` in `next.js`,below is steps how I went wrong.
I set `cssModules:true` in `next.config.js` like this.

```
const withLess = require('@zeit/next-less');

module.exports = withLess({
  cssModules: true
});
```
And,in `pages/homepage/index.js`  I simply write this without cssModule:

```
import Head from 'next/head';
import Link from 'next/link';

const Home = () => (
  <div>
    <Head>
      <title>homepage</title>
    </Head>

    <div>
      <div>title</div>
      <Link href="/func">
        <a>jump to func</a>
      </Link>
    </div>
  </div>
);

export default Home;
```
In my `/pages/func/index.js`,I write below with cssModule:

```
import React from 'react';
import styles from './index.less';

export default function Func() {
  return (
    <div>
      <div className={styles.textStyle}>func页面</div>
    </div>
  );
```
below is my `index.less` under `func` folder

```
.textStyle {
  color: red;
}
```
But,when I click `jump to func` Link In `/homepage` ,the router don't push to `/func`,something went wrong.And I tried many times finding that the `homepage`(the first page router to) must have below code In the head to fix the problem:
```
import styles from './index.less';
```
 even though I don't wanna use any styles In `homepage`.I think it's a bug in `next-less` which lies in cssModules and Link/Router conflict.

**Comment by mohammadou1** [comment]
Same issue here
