### ISSUE TITLE
How to change sourceMappingURL in bundled js

### ISSUE THREAD

**Issue by Chrischuck** [vercel/next-plugins#548]
I'm using `@zeit/next-source-maps v0.0.4-canary.1` to create source maps with the end goal of uploading the source maps to Sentry.

The issue is, when I upload the source maps to sentry, sentry gives the files a name such as `~/.next/static/pages/foobar.js.map` while the bundled js's `sourceMappingURL` is just `foobar.js.map`. 

In order to find the correct map file, Sentry looks at the `sourceMappingURL` and finds the corresponding name. The problem is that Sentry needs an exact match.

I have tried adding `SourceMapDevToolPlugin` to my plugins list to no avail. I either get the errors `compilation.getAsset is not a function` or `Error: write EPIPE`. It doesn't seem like there's settings in `@zeit/next-source-maps` to change this as well.

How can I change the `sourceMappingURL` in my bundled files?

Thanks!

**Comment by timneutkens** [comment]
Closing in favor of https://github.com/vercel/next.js/pull/20267
