### ISSUE TITLE
next-css - How to connect so that it would be possible to use both methods of connecting heart files, modular and ordinary?

### ISSUE THREAD

**Issue by sashaxxd** [vercel/next-plugins#549]
with the usual method, I import the css file
like this: import "../style.css"

When using the modular method as follows:
import classes from './ManufacturerList.module.css';

Accordingly, in jsx I deduce so

.example {
  font-size: 50px;
}

import "./style.css"

<div className = "example"> Hello World! </div>

with modular connection so
import css from "../style.css"

const Component = props => {
  return (
    <div className = {css.example}>
      ...
    </div>
  )
}

But it is necessary to register in next.config.js
cssModules: true

random prefixes are added to classes everywhere and in the usual way of connecting
(import "../style.css" - I do not need this)

and in a modular connection method
(import classes from './ManufacturerList.module.css';)

How to prevent random prefixes from being added to regular imports?

**Comment by sashaxxd** [comment]
Stumbled upon this discussion https://github.com/zeit/next-plugins/issues/403
All the same, I didn’t understand anything)))

we have the 'Component.module.css' processed as CSS module and 'Component.css' processed as plain CSS. Can we have that feature with this plugin? Thanks.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
