### ISSUE TITLE
CSS variable + calc + negative value crashes

### ISSUE THREAD

**Issue by nixolas1** [vercel/next-plugins#552]
Doing `calc(var(--myVar) * -1)` where `myVar` is a rem value crashes the compilation, only during production builds.

Full example:
`
:root {  --border-size: 1rem }
.box { border-width: calc(var(--border-size) * -1) }
`

I'm using v1.0.1 and css modules

Full console error log:
`$ next build && next export
Creating an optimized production build ...

> Using external babel configuration
> Location: "./web/.babelrc"
Failed to compile.

./styles/shared.module.css
ParserError: Syntax Error at line: 1, column 25
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)

> Build error occurred
Error: > Build failed because of webpack errors
    at build (./node_modules/next/dist/build/index.js:7:847)
error Command failed with exit code 1.
`
(there is no buggy code in line 1, column 25 of my css file.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
