### ISSUE TITLE
next-source-maps gives error for @charset "UTF-8"

### ISSUE THREAD

**Issue by kartikag01** [vercel/next-plugins#553]
Failed to compile.\n\n./base.css 1:0\nModule parse failed: Unexpected character \'@\' (1:0)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n> @charset "UTF-8";\n| body {\n|   background-color: #f1f3f4 !important;\n\n> Build error occurred\nError: > Build failed because of webpack errors\n    at build (/project/node_modules/next/dist/build/index.js:7:847)

**Comment by zhangwei900808** [comment]
same error!

**Comment by IronSean** [comment]
Also experiencing this.

**Comment by timneutkens** [comment]
Closing in favor of https://github.com/vercel/next.js/pull/20267
