### ISSUE TITLE
Can't change location of postcss.config.js

### ISSUE THREAD

**Issue by Organizzzm** [vercel/next-plugins#557]
Postcss-loader permits us to choose a custom directory for **_postcss.config.js_**
https://github.com/postcss/postcss-loader#config
But in **_css-loader-config.js_** checks only webpack context and breaks this feature.
`const postcssConfig = findUp.sync('postcss.config.js', {
    cwd: config.context
  })`
Postcss config may calls as .postcssrc.js as well.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
