### ISSUE TITLE
[next-css] not yet published to npm stable channel with minified css feature

### ISSUE THREAD

**Issue by rashidul0405** [vercel/next-plugins#558]
Hi,

I see many users facing "unminified css" issue on production when using `next-css` including us.

There is a commit merged to canary branch [8 months ago](https://github.com/zeit/next-plugins/commit/dc3b9b7d574c6030a7ba202f1dbc8f3b2b3ea62e#diff-0cebf7c341b5935cf4f071148eb666c4) but not yet published to [npm stable channel](https://www.npmjs.com/package/@zeit/next-css)

Latest version is `1.0.1`

Is it possible to publish the latest code with optimization feature enabled?

Thanks

**Comment by sheerun** [comment]
We also need it. Also, there is the source of `@zeit/next-sass@1.0.1`? The source doesn't show it: https://github.com/zeit/next-plugins/tree/master/packages/next-sass

A little bit of love for this repository would be nice, the commits and releases are very rare

**Comment by timneutkens** [comment]
Closing in favor of https://github.com/vercel/next.js/pull/20267
