### ISSUE TITLE
[next-sass] Styles dowloaded multi-times in dev

### ISSUE THREAD

**Issue by aralroca** [vercel/next-plugins#559]
Using the next-sass plugin, sometimes it's downloading the styles multi-times in dev, with different epoch's:

![image](https://user-images.githubusercontent.com/13313058/67946646-0ebda100-fbe2-11e9-944d-724df8f331f3.png)

However, this is not always happening, only sometimes! Comparing all files, they are always identical. This issue is quite annoying, but everything keeps working.

Versions used:

```json
{
"@zeit/next-sass": "1.0.2-canary.2",
 "next": "9.1.2",
}
```

Any idea about what is this happening? Thank you!

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
