### ISSUE TITLE
Less with Link

### ISSUE THREAD

**Issue by mohammadou1** [vercel/next-plugins#560]
in my index.js

am importing less file
``` import 'style.less'```

but if am at page B then navigate to index

less file causes an issue :(

**Comment by mohammadou1** [comment]
https://nextstore.itmohou.now.sh/brands

an example is here
if you start at index directory everything works fine

but go to any page then go back to index and it gets stuck because of less file

**Comment by mohammadou1** [comment]
```
  return withManifest(
    withOffline(
      withCSS(withLess({
        lessLoaderOptions: {
          javascriptEnabled: true,
          modifyVars: themeVariables
        },
        manifest: {
          ...manifest
        },
        ...nextConfig
      }
      ))
    ));
```
this is my next.config

**Comment by gurmeetsinghmalhotra** [comment]
I think you'll need to include a blank(file with no contents) .less file in other pages as well
