### ISSUE TITLE
next-sass no live reload

### ISSUE THREAD

**Issue by ShreyKumar** [vercel/next-plugins#561]
Hi, I'm not sure if this is expected behaviour but it seems that live reload does not work with next-sass. This would make development very difficult for me so appreciate any assistance.

```
import React from 'react'
import Layout from '../components/Layout'
import Footer from '../components/Footer'

import '../styles/index.scss' // commenting this file would not remove the styles unless the server is manually restarted

const Home = () => (
    <Layout>
          test
    </Layout>
)

export default Home;
```

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
