### ISSUE TITLE
next-source-maps should be installed in dev deps

### ISSUE THREAD

**Issue by Vadorequest** [vercel/next-plugins#562]
https://github.com/zeit/next-plugins/tree/master/packages/next-source-maps 

Doesn't seem useful to me to install this package as a deps, but rather as a dev deps. Or am I wrong?

Also, this documentation is valid with `"@zeit/next-source-maps": "0.0.4-canary.1",` only, not with 0.0.3 which is the one that'll be installed when running `yarn add -D @zeit/next-source-maps`, and that should be specified in the doc.

**Comment by offero** [comment]
From what I gather, this is meant for use in production deployments.

My question is, how/should we enable it also in development (NODE_ENV='development' or webpackConfig dev==true)?

**Comment by nodabladam** [comment]
I install this as dev dependency and then do something like this:

```
const {
  PHASE_DEVELOPMENT_SERVER,
  PHASE_PRODUCTION_BUILD
} = require("next/constants");

//  next-less, next-css, etc only need require duing dev/build
// https://github.com/zeit/next.js/issues/4248#issuecomment-386038283
module.exports = phase => {
  if (phase === PHASE_DEVELOPMENT_SERVER || phase === PHASE_PRODUCTION_BUILD) { 
    const withSourceMaps = require("@zeit/next-source-maps")();
    return withSourceMaps({...nextConfig}) 
  } else {
    return nextConfig;
  }
};
```
