### ISSUE TITLE
next-sass compile error, 'child_process' in 'worker-farm' not found

### ISSUE THREAD

**Issue by matkoson** [vercel/next-plugins#564]
Hi,

I can't manage to set up sass plugin with my current Next settings. The issue is that when I am trying to compile my app, the following error is thrown
![Annotation 2019-11-13 130334](https://user-images.githubusercontent.com/41837132/68762449-79c19b80-0616-11ea-8c6a-8ea57cceb982.png)

I couldn't find any solution either on the web or in currently existing issues.

My `package.json`

```
{
	"scripts": {
		"dev": "next",
		"build": "next build",
		"start": "next start"
	},
	"dependencies": {
		"@zeit/next-css": "^1.0.1",
		"@zeit/next-sass": "^1.0.1",
		"isomorphic-unfetch": "^3.0.0",
		"lodash": "^4.17.15",
		"next": "latest",
		"node-sass": "^4.13.0",
		"react": "^16.7.0",
		"react-dom": "^16.7.0"
	},
	"devDependencies": {
		"@testing-library/jest-dom": "^4.2.3",
		"@testing-library/react": "^9.3.2",
		"@types/jest": "^24.0.21",
		"@types/node": "^12.12.7",
		"@types/reach__router": "^1.2.6",
		"@types/react": "^16.9.11",
		"@types/react-dom": "^16.9.3",
		"@typescript-eslint/eslint-plugin": "^2.6.1",
		"eslint-config-prettier": "^6.1.0",
		"eslint-config-recommended": "^4.0.0",
		"eslint-plugin-react": "^7.14.3",
		"eslint-plugin-react-hooks": "^2.0.1",
		"prettier": "^1.18.2",
		"prop-types": "^15.7.2",
		"react-redux": "^7.1.0",
		"redux": "^3.6.0",
		"redux-devtools-extension": "^2.13.2",
		"redux-thunk": "^2.3.0",
		"typescript": "^3.7.2"
	}
}


```
`next.config.js`
```
const withSass = require('@zeit/next-sass');

exports.default = withSass({
	env: {
		DEV: true
	}
});

```

The entire repo is available at https://github.com/matkoson/next-sass-bug-repro

How to reproduce: `yarn` => `yarn dev`

All is working fine when I get rid of withCSS wrapper.

Please help.

**Comment by jamesmosier** [comment]
Are you trying to use `@zeit/next-css` or `@zeit/next-sass`?

In your example repository, I only see `@zeit/next-css` in your `next.config.js`, which won't work for `.scss` files. If you want to use SASS, you will need to use the [next-sass](https://github.com/zeit/next-plugins/tree/master/packages/next-sass) package.

**Comment by matkoson** [comment]
Hi @jamesmosier ,

Thank you for the reply. I should mention I was experiencing exactly the same issue with css plugin as well. I have already pushed changes to the repo, now it uses `next-sass`

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
