### ISSUE TITLE
Dynamic css option

### ISSUE THREAD

**Issue by jatinvmehta** [vercel/next-plugins#566]
Currently we have white label application written in React.js (15.2). This application has one codebase and serve 6 different content site and pick up right CSS based on domain name. This application is written using SSR and we are getting lot of issues with this. We are planning to rewrite this application using Next.js as SEO is pretty important for us. As it is one codebase and 6 different site level CSS require, what is best option for us ? If there is any good example or article available, please share.
In our current app, we are injecting css path dynamically based on domain name, how can we achieve this with Next.js ?

**Comment by jamesmosier** [comment]
It would be better to post this in the [Spectrum chat](https://spectrum.chat/next-js/general?tab=posts). It is better for discussions like this.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
