### ISSUE TITLE
Styles not loading in the preview mode of dev tools

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [vercel/next-plugins#567]
I am using "@zeit/next-sass": "^1.0.1"

When I open dev tools and try to preview the page load. The whole page is broken and loaded without CSS in that preview window. Although, the page loads fine in the browser window. What is the reason for this and what are the possible solutions and how does it affect my site?

https://ibb.co/nzf9VSn

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
