### ISSUE TITLE
Page or component level scss import in Nextjs

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [vercel/next-plugins#568]
I am using next.js in one of my projects with next-sass.

I have 2 pages /index and /about.

I have a .scss file that is being used for styling index page and when included in index.js everything works as expected. Since the scss is just being used for the index page or a particular component of the index page. When a user directly lands on "/about" page the CSS from .scss file being included in the index is also present in the final CSS bundle. But I am not sure whether the user will go back to /index or not. So, why load that extra scss on /about?

How can we write component level or page level scss?

Shouldn't the scss be loaded only if that page/component is being loaded? Because if I have multiple pages then all of their css will be loaded on a single page. Or I am thinking too much and this is how it's supposed am using next.js in one of my projects with next-sass.

**Comment by genesisneo** [comment]
I believe I have the same issue. I post a StackOverflow question as well. 😞
https://stackoverflow.com/questions/60752431/nextjs-component-level-sass-styling

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
