### ISSUE TITLE
next-css update

### ISSUE THREAD

**Issue by michu2k** [vercel/next-plugins#569]
Hello 
Can you please update next-css config & dependencies? A new version of `extract-css-chunks-webpack-plugin` package is available, which introduces `ignoreOrder` option and it would be great if this option was available in this plugin.

**Comment by ppsirius** [comment]
Last update was 9 months ago :[

**Comment by kachkaev** [comment]
@michu2k if you are just using css and don't need less/sass, how about trying `experimental: { css: true }`? See https://github.com/zeit/next.js/issues/8626 and https://github.com/zeit/next.js/pull/8710.

That said, I think it would be valuable to release new versions of `next-css`, `next-less` and `next-sass` plugins. Despite that the built-in support is coming in future, certain scenarios are getting pretty painful today. So a simple dependency update in plugins would be a huge relief to many of us 🙏

**Comment by michu2k** [comment]
Thanks @kachkaev for the answer. I really appreciate your help, but I'm using sass in my project.

**Comment by KennyWho** [comment]
`extract-css-chunks-webpack-plugin` the latest version is 4.7.1，but in this repos use 3.7.1，this version has some issue likes [#174](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/174), I fork the project, and fix it in local, but I wish it can be updated

**Comment by felixmosh** [comment]
I ended up forking `next-css` and installing the package from github directly.
:\

**Comment by drewlustro** [comment]
Ugh... doesn't look like this is ever going to get an update.

They're fixated on zeit/next.js#8626 :(

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.

**Comment by kachkaev** [comment]
@timneutkens unfortunately we still need plugins for projects using less. It’d be great to get some attention to these, which would involve upgrades to the plugins. I know that using CSS modules or styled-components is better, but it’s not always possible.

An example of a hard dependency on less is [ant design](https://github.com/ant-design/ant-design). That library is very popular (55K github stars) and the integration between it and Next is quite painful at the moment. Deprecation of next-css and next-less makes things worse in the long run as they are currently needed for the setup.
