### ISSUE TITLE
Change compilation directory of next sass

### ISSUE THREAD

**Issue by gurmeetsinghmalhotra** [vercel/next-plugins#573]
I want to change the compilation directory of next sass from ".next/static/css" to something custom so that I can include it myself wherever I want instead of  next doing it for me.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
