### ISSUE TITLE
Importing CSS stylesheet of semantic-ui causes loader exception

### ISSUE THREAD

**Issue by maitNoserYoung** [vercel/next-plugins#575]
After installing and configuring withCSS, the following error occures when trying to import the css file of semantic-ui-css

## CSS import
`import 'semantic-ui-css/semantic.min.css'`
## next.config.js
`const withCss = require("@zeit/next-css");
const withSass = require("@zeit/next-sass");
module.exports = withSass(withCss({}));`
## Error
`[ error ] ./node_modules/semantic-ui-css/semantic.min.css
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See http
s://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
`

**Comment by jffin** [comment]
I had same issue but seems like adding "cssModules: true" to config helps to solve it.
But now it stucks on compiling pages.

**Comment by RodolfoGS** [comment]
Same issue

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
