### ISSUE TITLE
withSass + "cssModules: true" broken ? no output and no visible errors 

### ISSUE THREAD

**Issue by orenmizr** [vercel/next-plugins#578]
it simply produces no css. 

versions: 
```
    "@zeit/next-css": "*",
    "@zeit/next-sass": "*",
    "isomorphic-unfetch": "^3.0.0",
    "next": "9.1.4",
    "node-sass": "^4.13.0",
    "react": "16.12.0",
    "react-dom": "16.12.0"
```

- without css modules it works. 
- attempted installing different css loader versions: did not work
- attempted withSass npm package that is not zeit's. did not work.

any ideas ?

**Comment by derit** [comment]
i found error with ````    cssModules: true``` 
```
Module not found: Can't resolve 'css-loader/locals'
```

on using options

```
cssLoaderOptions: {
      importLoaders: 2,
     localIdentName: "[local]___[hash:base64:5]"
    }
```

localIdentName error too

**Comment by orenmizr** [comment]
@derit did you try to downgrade the css loader as suggested in many places ?

**Comment by Soundvessel** [comment]
I am also getting this error with a codesandbox (https://codesandbox.io/s/sharp-tdd-pirjk?fontsize=14&hidenavigation=1&theme=dark) while trying a solution found here for Global SASS + modules. https://github.com/zeit/next-plugins/issues/149#issuecomment-526881653

**Comment by Soundvessel** [comment]
Make sure you are not using something like codesandbox.io. I was getting the `localIdentName ` error as described above but once I tried locally I had no issue. Those sandbox sites are nice but I am finding they breakdown in some instances even though the code and dependancies are the same.

**Comment by derit** [comment]
this is issue because i using yarn workspace and i have 2 project in workspace create-react-app and nextjs app

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
