### ISSUE TITLE
withSass: `cssLoaderOptions` are messy

### ISSUE THREAD

**Issue by judehunter** [vercel/next-plugins#579]
`cssLoaderOptions` should not be different from the ones defined by [the actual module](https://github.com/webpack-contrib/css-loader#options).

The way the current options work is confusing. For example, I could not get why this would not work:
```js
cssLoaderOptions: {
  localsConvention: 'camelCase',
}
```
Instead I had to guess to do this:
```js
cssLoaderOptions: {
  camelCase: true,
}
```
Also this way prevents me from setting the convention to `camelCaseOnly`

Another example:
```js
cssLoaderOptions: {
  localIdentName: '[local]___[hash:base64:5]',
}
```
should really be (according to css-loader):
```js
cssLoaderOptions: {
  modules: {
    localIdentName: '[local]___[hash:base64:5]',
  }
}
```

This also confused me, because the css-loader options are linked in the readme:
![image](https://user-images.githubusercontent.com/32528507/70845091-cdf4b100-1e4a-11ea-9c6b-2acddca209c5.png)

Is there a reason behind this design choice?

**Comment by ivantm** [comment]
Hi @judehunter, 

You're probably looking at the [latest docs for css-loader](https://github.com/webpack-contrib/css-loader#options) (at the time of writing, v3.x) and the [dependency in package.json for the next.js plugin is 2.1.0](https://github.com/zeit/next-plugins/blob/master/packages/next-css/package.json#L8). 

Among the breaking changes between v2 and v3 of cssLoaderOptions were config changes like the one you observed. If you look at the v2 docs, you'll see the options that the plugin will currently work with.

Ideally, we'd see these plugins be updated relatively quickly after new versions of webpack loaders come out. Or, at the least, the README.md would link to the docs for the correct version, though remembering to do that could be error-prone 😃

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
