### ISSUE TITLE
Cannot load css from node_modules, no error message

### ISSUE THREAD

**Issue by tim-phillips** [vercel/next-plugins#580]
When I add `import react-day-picker/lib/style.css`, the page that this component is on will not load during client-side routing and there is no error or anything else to indicate what is wrong. It does load if you visit `/day` directly. Also, removing the import allows the route to load. 

Reproduced in this repo:
https://github.com/tim-phillips/nextjs-css

This solution does not work: https://github.com/zeit/next-plugins/issues/70#issuecomment-474722343

**Comment by Cheau** [comment]
Yeah, I'm also facing this issue.

When switching to a page that import a css file, the script of that page is successfully loaded by the page-loader of client, however, the css file is not loaded. Then the router do not change and no any information is prompted.

I've tried to figure it out in a tricky way by using `next/dynamic` to import such a component like below:
```jsx harmony
// my-page.js
import dynamic from 'next/dynamic'

const MyComponent = dynamic(() => import('path/to/ComponentWithCss'), { ssr: false })

export default () => (
    <div>
        <MyComponent />
    </div>
)
```

Hope this issue could be fixed.

**Comment by damien-monni** [comment]
Same error for me trying to import Quill CSS from node_modules:

```
import 'quill/dist/quill.core.css';
```

**Comment by linainvers** [comment]
I fixed a similar problem when export components from dynamic folders.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
