### ISSUE TITLE
why extract-css-chunks-webpack-plugin is disable for server side? 

### ISSUE THREAD

**Issue by videni** [vercel/next-plugins#583]
I am using css module, when do server side rendering, I need to export my css files into a file, then use it in my component, why this is disabled?

https://github.com/zeit/next-plugins/blob/82e944a271c25cba7706db66b01d7e35b534aee1/packages/next-css/css-loader-config.js#L111

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
