### ISSUE TITLE
[next-sass] allow use `sass` replace `node-sass`

### ISSUE THREAD

**Issue by bluelovers** [vercel/next-plugins#590]
hope can allow use `sass` replace `node-sass`

**Comment by tingtingtinghuang** [comment]
How about this:
```
withSass({
 sassLoaderOptions: {
    implementation: require('sass')
  }
})
```

**Comment by bluelovers** [comment]
why not let it auto handle, let user just need choose install node-sass or sass

**Comment by in-in** [comment]
This doesn't work for me
```js
// next.config.js
const withSass = require('@zeit/next-sass');
const sass = require('sass');

module.exports = withSass({
	cssModules: true,
	sassLoaderOptions: {
		implementation: sass,
	},
});
```  
```shell
Error: Cannot find module 'node-sass'
```

```json
"@zeit/next-sass": "1.0.1",
"sass": "1.25.0"
```

**Comment by bluelovers** [comment]
@in-in before they take this pr

u can try use this code in `package.json` and use `yarn`

```json
"dependencies": {
"node-sass": "npm:sass"
}
```

**Comment by tingtingtinghuang** [comment]
@in-in  I test the config locally, it works. 
By the way, does your project work with node-sass?

**Comment by in-in** [comment]
Yes _Sass_ files compiles without any problems with `node-sass` ("4.13.1")

**Comment by chrisandrewca** [comment]
@tingtingtinghuang Could you post your package.json and next.config?

I'm using
`module.exports =
  withBundleAnalyzer(
    withSass({
      webpack(config, ) {
        config.node = {
          fs: 'empty'
        };
        return config;
      },
      sassLoaderOptions: {
        implementation: require('sass')
      }
    }));`

`    "@zeit/next-sass": "^1.0.1",
    "sass": "^1.25.0"`

and also get the error:  `Error: Cannot find module 'node-sass'`

**Comment by tingtingtinghuang** [comment]
@chrisandrewca 
```
 "sass": "1.14.1",
 "sass-loader": "7.1.0"
```
Remember to add sass-loader in dependencies.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
