### ISSUE TITLE
NextCSS: Warning: Prop `className` did not match

### ISSUE THREAD

**Issue by rjoaopereira** [vercel/next-plugins#595]
**Warning: Prop `className` did not match** 

This error has a lot of hits in nextjs issues and the source of the problem can vary.
I am opening this issue as I haven't seen this problem described before.

**Stack**

|  library  | version  |  Notes | 
|---|---|---|
| Nextjs | 9.1.7  | (Problem happens >=8 but not in 7 ) |
|next-transpile-modules | 2.3.1 | |
| @zeit/next-css | 1.0.2-canary.2 | |

**Problem**
importing external components built with css modules will raise the above error.

**Analysis**

NextJS webpack config's [mainFields](https://github.com/zeit/next.js/blob/v9.1.7/packages/next/build/webpack-config.ts#L244) are different between server and client.

cssloader uses the file path to generate the [hash](https://github.com/webpack-contrib/css-loader/blob/v1.0.0/lib/getLocalIdent.js#L21) for the className

**The problem does not happen if the component file is imported through a relative path instead of using its package name.**

**Solution**

Not the best one but as the plugin is not receiving updates we cannot pass a `customInterpolationName` in the loader `query`. As such, we need to go one step back and change the filename in the `getLocalIdent`

```js
const withCSS = require("@zeit/next-css");
const withTM = require("next-transpile-modules");
const getLocalIdent = require("css-loader/lib/getLocalIdent");
const path = require("path");

module.exports = withCSS(withTM({
    transpileModules: ["modulename"],
    cssModules: true,
    cssLoaderOptions: {
        importLoaders: 1,
        localIdentName: "[local]___[hash:base64:5]",
        getLocalIdent: (context, localIdentName, localName, options) => {
        const newContext = { ...context };
        if (newContext.resourcePath.includes("modulename")) {
            newContext.resourcePath = newContext.resourcePath.replace(
            `${path.sep}es${path.sep}`,
            `${path.sep}lib${path.sep}`
            );
        }
        return getLocalIdent(newContext, localIdentName, localName, options);
        }
    }
    })
);
```

I would like to see cleaner solutions to this problem if possible.

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
