### ISSUE TITLE
Failed loading of custom sass file in dev: first time only

### ISSUE THREAD

**Issue by albertosanfilippo** [vercel/next-plugins#601]
It happens only the first time I run server locally and land on a page. when changing page (that imports its own style.sass) it doens't load the last style. In the network i don't see another styles.chunk.css call and inspecting the existing the style.chunk in the network and looking for a class for example it isn't present. Seems like a cache problem.

When building the full package for production all the styles are present and so it works properly.
Thanks

**Comment by chrisandrewca** [comment]
I'm experiencing this as well.

**Comment by sangbpark94** [comment]
I am experiencing this as well. When I navigate using <Link /> the styles don't load for the page and I have to refresh :(

**Comment by sangbpark94** [comment]
Related to #561

**Comment by sangbpark94** [comment]
bump

**Comment by jon301** [comment]
I've just experienced this issue as well using `next-sass` with SCSS modules.
(For information I cannot use the built in CSS modules support from Next as I need to compile CSS modules from a UI library which is another package)

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
