### ISSUE TITLE
Can't import SCSS partials @import in one file to Next.js app

### ISSUE THREAD

**Issue by sanderyt** [vercel/next-plugins#602]
I have been trying to get SASS to work for a few days and would be grateful if someone could help me out. Within my Next.js app I have been styling components based on the BEM methodology. I import my SCSS partial files in one SCSS file called index.scss. This file is imported in "pages/index.js". The following error shows: 

_ModuleParseError: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)_

I guess because I use @import, it can't be compiled. Could somebody help me out configuring the next.config.js the right way for this? Can't seem to find the solution.

Sander

**Comment by cjpdesign** [comment]
I had same issue. This is how I solve it that you have to use next-compose-plugins to combine existing webpack. And I found out there is some weird issue of using url('./static/img.jpg') that I have to remove it to make it works.

```
const withPlugins = require("next-compose-plugins")
const withSass = require("@zeit/next-sass")
const path = require('path')

module.exports = withPlugins([withSass], {
	target: 'serverless',
	webpack(config) {
		config.resolve.modules.push(path.resolve('./'))
		return config
	}
})
```

**Comment by sanderyt** [comment]
It didn't work unfortunately. Still haven't figured out this issue. Shouldn't be that hard, right?

**Comment by sanderyt** [comment]
For people that want to know the solution, just install the next-sass plugin and import your main stylesheet in _app.js!
