### ISSUE TITLE
[next-css] CSS optimization in production

### ISSUE THREAD

**Issue by muhmushtaha** [vercel/next-plugins#604]
I see that you have the [optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) in the css loader configs and a lot of changes but when I install the package I can't see these changes in the installed module!

Are you sure you published the latest changes to npm modules?!

Here is the configs file that I have [css-loader-configs](https://repl.it/@MuhammedMushtah/css-loader-configs)

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
