### ISSUE TITLE
Can't get css modules to work for less files

### ISSUE THREAD

**Issue by tildahl199** [vercel/next-plugins#608]
Trying to get less files to load as css modules, so *.module.less but can't find a config that works. Tried the following config:

`module.exports = withPlugins([
  [withLess, {
    lessLoaderOptions: {
      javascriptEnabled: true,
      modifyVars: themeVariables,
    },
    cssModules: true,
    cssLoaderOptions: {
      importLoaders: 1,
      localIdentName: "[local]___[hash:base64:5]",
    },
  }],
  [withBundleAnalyzer],
], nextConfig);`

but doesn't work. Tried the webpack config suggested here [https://medium.com/@joseph0crick/react-css-modules-less-webpack-4-a50d902d0a3](url) as part of the webpack custom config in nextConfig but that didn't work either.

I can get *.module.css to work if I add the withCss plugin along with the withLess plugin, but haven't found a way to load less files as modules. Is this supported yet or not possible in Nextjs 9.2.1 yet?

**Comment by tildahl199** [comment]
I see modules are fixed for scss in 9.3.0 but not less. Any chance the same fix will be coming for *.module.less files too?

**Comment by xyy94813** [comment]
@tildahl199

You can reference my code and copy to your project.

https://github.com/xyy94813/next-plugins/blob/master/packages/next-less-modules/index.js.
