### ISSUE TITLE
recommended release version to use

### ISSUE THREAD

**Issue by nodabladam** [vercel/next-plugins#623]
I am confused about what version of these plugins the average user should be using.  npm is saying latest is`1.0.1` which most people will use but I suspect based on some comments I see in issues this is not recommended.  

npm says `0.2.1-canary.4` is the latest canary.  
gitub "releases" says latest build is `1.0.2-canary.2`

Can you please cut a 1.0.2 release to avoid any confusion about what really is recommended?

**Comment by timneutkens** [comment]
Hey! We're deprecating this repository, I just updated the readme.
