### ISSUE TITLE
Typo in stylus plugin readme 

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [vercel/next-plugins#628]
https://github.com/zeit/next-plugins/tree/master/packages/next-stylus

```javascript
// next.config.js
const nib = require('nib')
const rupture = require('rupture')
const withStylus = require('@zeit/next-stylus')
const poststylus = require('poststylus')
const autoprefixer = require('autoprefixer')

module.exports = withStylus({
  stylusLoaderOptions: {
    use: [
      nib(),
      rupture(),
      poststylus([
        autoprefixer({ flexbox: 'no-2009' }),
        require('postcss-css-variables'),
      ]),
  }
})
```

![image](https://user-images.githubusercontent.com/60403187/79064933-8aee0180-7cb5-11ea-8e8c-5df08871552e.png)

**Comment by gunzzblazzing** [comment]
I think I need to delete this project as the functionality has been super seeded by NPM Audit

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
