### ISSUE TITLE
Updating NextJS from 8 to 9.3.3 broke styling

### ISSUE THREAD

**Issue by davidgtu** [vercel/next-plugins#629]
I just updated nextjs from 8 to 9.3.3, and some of my styling broke.

Previously I was importing `.scss` files and they were locally scoped to their respective components.

After updating to 9.3.3, it seems that components with `classNames` that are named the same are now sharing styles, so that leads me to believe that something with the sass-loader or css-loader in `next.config.js` seems off.

this is my `next.config.js`

```js
const path = require('path');

const dotenv = require('dotenv');
const withSass = require('@zeit/next-sass');
const webpack = require('webpack');

const envConfig = dotenv.config();

const config = withSass({
	cssModules       : true,
	cssLoaderOptions : {
		modules       : true,
		sourceMap     : true,
		importLoaders : 1,
	},
	sassLoaderOptions: {
		includePaths: [path.resolve(__dirname, './')], //eslint-disable-line
	},

	useFileSystemPublicRoutes: false,

	webpack: (config, { buildId, dev, isServer, defaultLoaders }) => { // eslint-disable-line
		const ENV = {};

		for (let entry in envConfig.parsed) {
			ENV[`process.env.${entry}`] = JSON.stringify(envConfig.parsed[entry]);
		}

		config.plugins.push(new webpack.DefinePlugin(ENV));

		return config;
	},
});

module.exports = config;
```

### What I've tried
I've changing my config around like this: 

```js
const config = withSass({
	cssModules       : true,
	cssLoaderOptions : {
		modules       : {
			mode: 'local',
			exportGlobals: true,
			localIdentName: '[path][name]__[local]--[hash:base64:5]',
            context: path.resolve(__dirname, 'src'), //eslint-disable-line
            hashPrefix: 'my-custom-hash',
		},
		sourceMap     : true,
		importLoaders : 1,
	},
	sassLoaderOptions: {
		includePaths: [path.resolve(__dirname, './')], //eslint-disable-line
	},

	useFileSystemPublicRoutes: false,

	webpack: (config, { buildId, dev, isServer, defaultLoaders }) => { // eslint-disable-line
		const ENV = {};

		for (let entry in envConfig.parsed) {
			ENV[`process.env.${entry}`] = JSON.stringify(envConfig.parsed[entry]);
		}

		config.plugins.push(new webpack.DefinePlugin(ENV));

		return config;
	},
});

module.exports = config;
```

which didn't work.

My last resort which **does** work is manually going into each `.scss` file and changing them to `x.module.scss`, which would take a lot of time going into each file. Is there something wrong with my config?

**Comment by Timer** [comment]
If you're using `next-sass`, it should be disabling the built-in CSS support.

We'll need a completely reproducible demo if something is broken for you!

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
