### ISSUE TITLE
Why you changed 'pure' mode for css-modules?

### ISSUE THREAD

**Issue by 7iomka** [vercel/next-plugins#635]
Why you changed 'pure' mode for css-modules?
It's safe if I remove it from my config?
like `delete loaderItem.options.modules.mode;`

I have a need to determine the behavior of component (module) styles depending on the parent global className (for ex: .layout--with-sidebar)
With 'pure' option this code won't wok: `:global(.layout--with-sidebar) .header {...}`
because :global is not not allowed.
Thanks!

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
