### ISSUE TITLE
next new version next-css error 

### ISSUE THREAD

**Issue by ebs-PriyankaKanwar** [vercel/next-plugins#639]
I have using next-CSS but they are giving me a warning and when I removed the next-CSS from next.config.my style CSS is not loaded chunks in the production.
Can you plz help me.

**Comment by nvbinh** [comment]
Same for me. Not only nextCss, nextLess, nextSass are the same :|

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
