### ISSUE TITLE
extract-css-chunks-webpack-plugin is disabled when using withSass

### ISSUE THREAD

**Issue by yanv1991** [vercel/next-plugins#643]
Looks like when add this plugin the css code splitting is not happening, maybe this needs to be applied manually when using withSass
![Screen Shot 2020-05-29 at 1 39 28 PM](https://user-images.githubusercontent.com/3800032/83288803-f92d4b80-a1b1-11ea-8c68-adad0efb273e.png)

here is a reproducible repo: https://github.com/yanv1991/demo-react-dom/blob/master/next.config.js

expected: the css generated by dynamic chunks should be in a separated css file,
result: getting a single style file with all the css

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
