### ISSUE TITLE
How to activate autoprefixer using next-sass

### ISSUE THREAD

**Issue by SashimiBites** [vercel/next-plugins#658]
Hi, im currently trying to activate autoprefixer using the next-sass plugin, and i cant see how it should work, what i got right now is this: 
postcss.config.js - 
`module.exports = {
  plugins: [require("autoprefixer")]
};`

next.config.js - 
`const withSass = require('@zeit/next-sass');
module.exports = withSass({
});`

package.json -
`{
  "name": "new-web",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "autoprefixer": "^9.8.6",
    "next": "9.5.1",
    "node-sass": "^4.14.1",
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "browserslist": [
    ">0.3%",
    "not ie 11",
    "not dead",
    "not op_mini all"
  ]
}`

if you can help me how to aproach this would be cool

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.
