### ISSUE TITLE
Customize mini-css-extract-plugin in withCss

### ISSUE THREAD

**Issue by reallifeliver** [vercel/next-plugins#659]
Hi. I got warning below

```
 chunk styles [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./src/components/common/profile/group/~~.scss
 * css ./node_modules/@zeit/next-css/node_modules/css-loader??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./src/components/common/profile/group/~~~.scss

```

In my project, the order of scss files is not important. because they are totally independent. So, I don't need this warning. And this warning log can be turned off by adding ` ignoreOrder: true` option in `mini-css-extract-plugin`.

To try this option, I have to customize mini-css-extract-plugin that withCss plugin uses inside. But when I read this source, I can find no way to customize default mini-css-extract-plugin by options. 

What should I do add ` ignoreOrder: true` option of mini-css-extract-plugin?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
