### ISSUE TITLE
@zeit/next-workers: ValidationError: Invalid options object.

### ISSUE THREAD

**Issue by SkrewEverything** [vercel/next-plugins#663]
[worker-loader](https://github.com/webpack-contrib/worker-loader) released a new major update [v3.0.0](https://github.com/webpack-contrib/worker-loader/releases/tag/v3.0.0) on 2020-08-01. This update doesn't work with @zeit/next-workers@1.0.0 anymore.

The error it produces is:

```
error - 
ValidationError: Invalid options object. Worker Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'name'. These properties are valid:
   object { worker?, publicPath?, filename?, chunkFilename?, inline?, esModule? }
```

In worker-loader@3.0.0, `name` is renamed to `fileName` like mentioned in the [changelog](https://github.com/webpack-contrib/worker-loader/releases/tag/v3.0.0).

There are 2 solutions:

1. Only use worker-loader@2.0.0 instead of v3.0.01. 

2. Just change the `name` to `fileName` at [line#14](https://github.com/vercel/next-plugins/blob/master/packages/next-workers/index.js#L14)  in the source of @zeit/next-workers.

There are so many pending pull requests in this repo. So, I'm skeptical about the team accepting my pull request. So, this might help future developers who are having this issue.

If the maintainers come across this, please update the readme with this or even better update the plugin to use the latest worker-loader v3.0.1.

**Comment by SkrewEverything** [comment]
@stuartmemo I haven't explored other options as I've just reverted back to worker-loader@2.0.0 as it was enough for my use case. But it's not that hard to use webpack loaders in Next.js by yourself. I'm positive there would be plenty of loaders for webpack and you can follow this guide [Custom Webpack Config](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config) to use that webpack loader in your Next.js.

**Comment by stuartmemo** [comment]
Amazing, thanks for the pointer. That was remarkably easy. For those following along at home, just remove the plugin and add this to your `next.config.js`...
```
    webpack: (config) => {
        config.module.rules.push({
            test: /\.worker\.js$/,
            use: { loader: 'worker-loader' },
        });

        return config;
    }
```
