### ISSUE TITLE
CSS does not load from components imported from _document.js

### ISSUE THREAD

**Issue by jamesplease** [vercel/next-plugins#670]
# Bug report

## Describe the bug

`_document.js` can import other component files. However, if those components import CSS, the contents of the CSS files are not injected in the compiled stylesheet.

Similarly: importing global CSS files from components imported from `_document.js` does not throw the same error as when they are imported from, say, `_app.js` (no error is thrown when global CSS is imported from `_document.js`)

## To Reproduce

1. Create a component, say, `components/button.js` that imports styles from `components/button.styles.css`.
2. Import and render this component in `_document.js`
3. Observe that the button's class name is applied in the rendered HTML, but that the CSS is not imported

## Expected behavior

One of two things:

- The CSS would be loaded
- An error would be thrown, letting you know that this configuration is invalid

## Screenshots

N/A

## System information

- OS: macOS
- Browser: Any
- Version of Next.js: 9.3.1

## Additional context

N/A

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
