### ISSUE TITLE
Source maps resolved wrongly @zeit/next-source-maps

### ISSUE THREAD

**Issue by Joozty** [vercel/next-plugins#678]
I have a route like `/test/[id].jsx` and when I import css module in that file it source map is resolved relative to that part, i.e. `/test/sourcemap.css.map`

![sourcemaps](https://user-images.githubusercontent.com/12775440/98540115-b6f25500-228d-11eb-9366-ef156fa163e7.PNG)

### Steps to reproduce:
1. Clone [this repo ](https://github.com/Joozty/next-source-maps-resolve)
2. Run `npm ci`, `npm run build`, `npm run start`
3. Open in your browser localhost:3000/test/1
4. Open the dev console and see the same warning as attached image.

Thanks a lot for looking into it.

**Comment by kachkaev** [comment]
That package is probably no longer supported. Try removing it and add `experimental` → [`productionBrowserSourceMaps`](https://github.com/vercel/next.js/search?q=productionBrowserSourceMaps) in your `next.config.js` instead.

**Comment by Joozty** [comment]
Alrighty then. Thanks for your help 🙂
