### ISSUE TITLE
@zeit/next-sass has to be updated to use node-sass v5

### ISSUE THREAD

**Issue by stomvi** [vercel/next-plugins#679]
Since `node-sass` and `sass-loader` have been updated. Suggesting update `next-sass` to use the latest versions.

**Comment by kachkaev** [comment]
Next.js has out-of-box sass support now: https://nextjs.org/docs/basic-features/built-in-css-support#sass-support

It might be worth considering a switch to that rather than sticking with the plugin. Note that you'll need to convert your styles into CSS modules.

**Comment by stomvi** [comment]
I found that I was actually using the built-in sass support.  Somehow let `next-sass v5` installed after `ncu` update made me confused.  I'll close this and thanks!
