### ISSUE TITLE
Style hot reload not triggered with legacy @zeit/next-css or @zeit/next-less plugins

### ISSUE THREAD

**Issue by ye-will** [vercel/next-plugins#681]
# Bug report

## Describe the bug

It seems that hot-reload of stylesheets haven't triggered properly with legacy style plugins such as @zeit/next-css or @zeit/next-less

## To Reproduce

With Gitpod: https://gitpod.io/#https://github.com/ye-will/next-broken-style

1. press `Broken` button, styles of the new page breaks.
2. refresh the browser, styles become correct.
3. change some code or restart the dev server, styles will broken again.

## System information

- OS: MacOS/Linux
- Browser (if applies): Chrome
- Version of Next.js: 10.0.1
- Version of Node.js: 12.0.0+
- Deployment: next dev

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
