### ISSUE TITLE
`localIdentName` default value for `dev`

### ISSUE THREAD

**Issue by bminer** [vercel/next-plugins#686]
It is not very easy to set `localIdentName` based on the WebPack `dev` flag.  I currently do this:

```js
webpack(config, options) {
	// Set `cssLoaderOptions.localIdentName` to something better for `dev`
	const { dev, defaultLoaders } = options
	if (dev) {
		const { stylus } = defaultLoaders
		if (stylus) {
			const cssLoader = stylus.find(
				u => u.loader && u.loader.startsWith("css-loader")
			)
			cssLoader.options.localIdentName = "[name]_[ext]__[local]"
		}
	}
	return config
}
```

This is less than ideal, and it would be nice if the `localIdentName` defaulted to something more human-readable when `dev` flag is set.  Perhaps, we set to `"[name]_[ext]__[local]"` or something?

**Comment by timneutkens** [comment]
Hi, thanks for creating an issue. We currently recommend using https://nextjs.org/docs/basic-features/built-in-css-support as zeit/next-css and zeit/next-sass have been deprecated in favor of the built-in support.
